=== MaximePinot/nutritionfactsorg-data/json/schemas/audio.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/audio.schema.json",
    "title": "Audio",
    "description": "A Audio article from nutritionfacts.org",
    "type": "object",
    "properties": {
       "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/audio\\/"
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
       "Description": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                },
                "Text": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html",
                "Text"
            ],
            "additionalProperties": false
        },
        "CoverImage": {
            "type": "object",
            "properties": {
                "Urls": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "minLength": 1,
                        "format": "uri",
                        "pattern": "^https:\\/\\/assets\\.nutritionfacts\\.org\\/"
                    },
                    "minItems": 1,
                    "uniqueItems": true
                }
            },
            "required": [
                "Urls"
            ],
            "additionalProperties": false
        },
        "Duration": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string",
                    "minLength": 3,
                    "pattern": "\\d+:\\d"
                }
            ]
        },
        "Download": {
            "type": "object",
            "properties": {
                "Url": {
                    "type": "string",
                    "minLength": 79,
                    "pattern": "^https:\\/\\/media.blubrry\\.com\\/nutritionfactswithdrgreger\\/.*\\.(mp3|m4a)"
                },
                "Size": {
                    "type": "object",
                    "properties": {
                        "Value": {
                            "type": "string",
                            "minLength": 1,
                            "pattern": "\\d\\.\\d"
                        },
                        "Unit": {
                            "type": "string",
                            "enum": ["MB"]
                        }
                    },
                    "required": [
                        "Value",
                        "Unit"
                    ],
                    "additionalProperties": false
                }
            },
            "required": [
                "Url",
                "Size"
            ],
            "additionalProperties": false
        },
        "Transcript": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string",
                    "minLength": 1
                }
            ]
        }
    },
    "required": [
        "Title",
        "Url",
        "UpdatedAt",
        "Description",
        "CoverImage",
        "Duration",
        "Download",
        "Transcript"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/audio/qa-with-dr-greger.json
{
  "Title": "Q&A with Dr. Greger",
  "Url": "https://nutritionfacts.org/audio/qa-with-dr-greger/",
  "UpdatedAt": "2020-06-25T07:00:38+00:00",
  "Description": {
    "Html": "<p>Dr. Greger takes a wide range of questions from listeners today from the ice bucket challenge, to the anti-microbial properties of silver, to nocturnal hypertension.</p>\n<p> </p>",
    "Text": "Dr. Greger takes a wide range of questions from listeners today from the ice bucket challenge, to the anti-microbial properties of silver, to nocturnal hypertension."
  },
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2020/02/185-720x720.jpg",
      "https://assets.nutritionfacts.org/2020/02/185-540x540.jpg",
      "https://assets.nutritionfacts.org/2020/02/185.jpg",
      "https://assets.nutritionfacts.org/2020/02/185-960x960.jpg",
      "https://assets.nutritionfacts.org/2020/02/185-768x768.jpg",
      "https://assets.nutritionfacts.org/2020/02/185-1024x1024.jpg",
      "https://assets.nutritionfacts.org/2020/02/185-500x500.jpg",
      "https://assets.nutritionfacts.org/2020/02/185-1200x1200.jpg"
    ]
  },
  "Duration": "35:10",
  "Download": {
    "Url": "https://media.blubrry.com/nutritionfactswithdrgreger/assets.nutritionfacts.org/2020/02/NF-185-Q-and-A-with-Dr.-G.mp3",
    "Size": {
      "Value": "32.2",
      "Unit": "MB"
    }
  },
  "Transcript": "[no transcript available]"
}
