=== MaximePinot/nutritionfactsorg-data/json/schemas/blog.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/blog.schema.json",
    "title": "Blog",
    "description": "A Blog article from nutritionfacts.org",
    "type": "object",
    "properties": {
        "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/blog\\/"
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
        "Author": {
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1,
                    "enum": [
                        "Michael Greger M.D. FACLM",
                        "Brenda Davis and Vesanto Melina",
                        "Joseph Gonzales, R.D.",
                        "Vesanto Melina"
                    ]
                }
            ]
        },
        "CoverImage": {
            "type": "object",
            "properties": {
                "Urls": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "minLength": 1,
                        "format": "uri",
                        "pattern": "^https:\\/\\/assets\\.nutritionfacts\\.org\\/"
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "Attribution": {
                    "type": "string",
                    "minLength": 0
                }
            },
            "required": [
                "Urls",
                "Attribution"
            ],
            "additionalProperties": false
        },
        "Content": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "Title",
        "Url",
        "UpdatedAt",
        "Author",
        "CoverImage",
        "Content"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/how-to-maximize-nutrient-absorption.json
{
  "Title": "How to Maximize Nutrient Absorption",
  "Url": "https://nutritionfacts.org/blog/how-to-maximize-nutrient-absorption/",
  "UpdatedAt": "2017-11-14T13:00:58+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-960x540.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-1024x576.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-720x405.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-356x200.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-768x432.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-540x304.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-928x522.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green.jpeg",
      "https://assets.nutritionfacts.org/2017/11/11-28-Downside-of-Green-1200x675.jpeg"
    ],
    "Attribution": "Image Credit: MaxPixel. This image has been modified."
  },
  "Content": {
    "Html": "<p>Unhealthy lifestyle behaviors associated with an <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/20631456\">increased</a> risk of premature death include smoking, excessive alcohol drinking, and not eating enough greens. The best way to get your greens is in whichever way you’ll eat the most of them, and one way to sneak extra greens into your daily diet is with whole-food smoothies, “a potent blend of good nutrition” in a quick, portable, delicious form.  </p>\n<p>The Mayo Clinic offers a basic green smoothie recipe, combining the healthiest of fruits and the healthiest of vegetables, berries and dark green leafies, respectively. It calls for 2 ounces of baby spinach, which is about a cup and a half. Consider adding in some curly parsley, another mild beginner green to start with. Surprisingly, the sweetness of the fruit masks any bitterness from the greens such that the pickiest of children love these smoothies, as do adults who otherwise would not consume dark green leafy vegetables—or even fruit—for breakfast. Indeed, the average teen may only <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/25588935\">get</a> about 1/20th of a serving of fruit otherwise—and <i>Froot</i><i> L</i><i>oops</i> don’t count. </p>\n<p>Offering smoothies can have a dramatic effect on fruit consumption for “students who do not want to take time peeling or chewing fruits.” (Who doesn’t have time to chew a fruit?!) The milkshake-y texture of smoothies may not only boost the quantity of fruit and vegetable consumption, but also the quality. </p>\n<p>Carotenoid phytonutrients, like beta-carotene and lycopene, can exist as microscopic crystals <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22980866\">trapped</a> inside the cell walls of fruits and vegetables. They’re only <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/21535705\">released</a> when the cells are disrupted, which is why we have to chew really well. We either have to chew <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22806183\">better</a> or choose plants that are easier to chew. For example, while tomatoes have more beta-carotene than watermelon does, watermelon’s beta-carotene is more bioaccessible because its cell walls are wimpy compared with the smaller and tougher cell walls of other fruits and vegetables. To maximize nutrient release, food particle size would ideally be <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/23157717\">reduced</a> to smaller than the width of the individual plant cells, but you can’t do that with chewing. Most vegetable particles end up <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/15218050\">greater</a> than two millimeters when you chew them, whereas if we broke open all the cells, we could release much <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/21121612\">more</a> nutrition, as you can see in my video, <a href=\"https://nutritionfacts.org/video/are-green-smoothies-good-for-you/\"><b>Are Green Smoothies Good for You?</b></a>. The particle size distribution from chewing is about what you’d get blending in a food processor for about five seconds or one of those high-speed blenders for maybe half a second. Just 40 seconds in a blender can <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/14584601\">break</a> down spinach to a subcellular level. </p>\n<p>Why does that matter? Let’s look at folate, the B vitamin in greens that is especially important for women of child-bearing age. Feed people a cup of spinach a day for three weeks and their folate goes up compared to <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/11111131\">control</a>. What happens if you eat finely chopped spinach instead of whole leaves? You end up with more than twice as much in your bloodstream and the same absorption-boosting effect with lutein, the green nutrient so important for our eyesight.</p>\n<p>It’s not what you eat—it’s what you absorb.  </p>\n<p>The <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/10655967\">boost</a> for lutein was only 14%; so, a few extra bites of the whole leafy greens would have given you just as much. Some other nutrients, such as vitamin C, aren’t affected by pre-chopping at all. This is also less of an issue with cooked vegetables. If you boil carrots for three minutes, regular chewing can release about ten times more beta-carotene bioaccessibility than eating them raw, but not as much as <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/21121612\">blended</a>. Intense cooking, like boiling for 25 minutes, damages the cell walls so even gulping down large particles can result in significant absorption. But, blending may double carotenoid availability, explaining why we may be able to <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/11823572\">absorb</a> three times the alpha- and beta-carotene from pureed cooked carrots compared to mashed cooked carrots. So, blending vegetables—raw or cooked—into soups, sauces, or smoothies can maximize nutrient absorption. Whether you went to the store and bought it, or toiled in your garden to grow it, you might as well take full advantage of it.  </p>\n<hr/>\n<p>Check out my other videos that touch on smoothies:</p>\n<ul>\n<li><strong><a href=\"https://nutritionfacts.org/video/are-green-smoothies-bad-for-you/\">Are Green Smoothies Bad for You?</a></strong> </li>\n<li><a href=\"https://nutritionfacts.org/video/the-downside-of-green-smoothies/\"><strong>The Downside of Green Smoothies</strong></a> </li>\n<li><a href=\"https://nutritionfacts.org/video/a-better-breakfast/\"><strong>A Better Breakfast</strong></a></li>\n<li><a href=\"https://nutritionfacts.org/video/juicing-removes-more-than-just-fiber/\"><strong>Juicing Removes More Than Just Fiber</strong></a></li>\n</ul>\n<p>For other tips on getting children of all ages to eat healthier, see <a href=\"https://nutritionfacts.org/video/tricks-to-get-kids-to-eat-healthier-at-home/\"><strong>Tricks to Get Kids to Eat Healthier at Home</strong></a> and <a href=\"https://nutritionfacts.org/video/tricks-to-get-adults-to-eat-healthier/\"><strong>Tricks to Get Adults to Eat Healthier</strong></a>.</p>\n<p>Finally, learn more about the effect of cooking on nutrient loss and absorption from these videos: <a href=\"https://nutritionfacts.org/video/best-cooking-method/\"><strong>Best Cooking Method</strong></a>, <a href=\"https://nutritionfacts.org/video/raw-food-nutrient-absorption-3/\"><strong>Raw Food Nutrient Absorption</strong></a>, and <a href=\"https://nutritionfacts.org/video/sometimes-the-enzyme-myth-is-true/\"><strong>Sometimes the Enzyme Myth Is True</strong></a>.</p>\n<p>In health,<br/>\n <strong>Michael Greger, M.D.</strong></p>\n<p> PS: If you haven’t yet, you can subscribe to my free videos <a href=\"http://www.nutritionfacts.us5.list-manage.com/subscribe?u=c1bae6687e1e6ab175fb56913&amp;id=40f9e497d1\"><strong>here</strong></a><strong> </strong>and watch my live, year-in-review presentations:</p>\n<ul>\n<li>2012: <a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\"><strong>Uprooting the Leading Causes of Death</strong></a></li>\n<li>2013: <a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\"><strong>More Than an Apple a Day</strong></a></li>\n<li>2014: <a href=\"https://nutritionfacts.org/video/from-table-to-able/\"><strong>From Table to Able: Combating Disabling Diseases with Food</strong></a></li>\n<li>2015: <a href=\"https://nutritionfacts.org/video/food-as-medicine/\"><strong>Food as Medicine: Preventing and Treating the Most Dreaded Diseases with Diet</strong></a></li>\n<li>2016: <a href=\"https://nutritionfacts.org/video/how-not-to-die/\"><strong>How Not To Die: The Role of Diet in Preventing, Arresting, and Reversing Our Top 15 Killers</strong></a></li>\n</ul>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/which-nut-suppresses-cancer-cell-growth-the-most.json
{
  "Title": "Which Nut Suppresses Cancer Cell Growth the Most?",
  "Url": "https://nutritionfacts.org/blog/which-nut-suppresses-cancer-cell-growth-the-most/",
  "UpdatedAt": "2015-12-22T13:00:14+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2015/12/NF-Dec15-Which-Nut-Fights-Cancer-Better-768x334.jpg",
      "https://assets.nutritionfacts.org/2015/12/NF-Dec15-Which-Nut-Fights-Cancer-Better-320x139.jpg",
      "https://assets.nutritionfacts.org/2015/12/NF-Dec15-Which-Nut-Fights-Cancer-Better.jpg",
      "https://assets.nutritionfacts.org/2015/12/NF-Dec15-Which-Nut-Fights-Cancer-Better-300x130.jpg",
      "https://assets.nutritionfacts.org/2015/12/NF-Dec15-Which-Nut-Fights-Cancer-Better-460x200.jpg",
      "https://assets.nutritionfacts.org/2015/12/NF-Dec15-Which-Nut-Fights-Cancer-Better-1024x445.jpg"
    ],
    "Attribution": "Image Credit: Mariya Chorna / Flickr.  This image has been modified."
  },
  "Content": {
    "Html": "<p>People who eat nuts in their adolescence may have a better chance of fighting off breast cancer later in life, according to data from the <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/20229245\" target=\"_blank\" rel=\"noopener\">Harvard Nurse’s Study</a>. A <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/24043428\" target=\"_blank\" rel=\"noopener\">follow-up study</a> involving the daughters of the nurses corroborated the findings. Those eating more peanut butter, nuts, beans, lentils, soybeans, or corn were found to have just a fraction of the risk for fibrocystic breast disease, which places one at higher risk of cancer. The protective effects were found to be strongest for those most at risk, such as those with a family history of breast cancer.</p>\n<p>Another<a href=\"http://www.ncbi.nlm.nih.gov/pubmed/24149179\" target=\"_blank\" rel=\"noopener\"> study</a> out of the <em>British Journal of Cancer</em> found that even two handfuls of nuts a week may protect against pancreatic cancer, one of our most fatal malignancies.</p>\n<p>Nuts are <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/24176559\" target=\"_blank\" rel=\"noopener\">described</a> as “nutritionally precious,” which may explain some of the mechanisms by which nut components induce cancer cell death and inhibit cancer growth and spread <em>in vitro</em>. But which nuts work the best? In terms of antioxidant content, walnuts and pecans steal the show. Twenty-five walnuts <a href=\"http://www.sciencedirect.com/science/article/pii/S0023643808001771\" target=\"_blank\" rel=\"noopener\">have</a> the antioxidant equivalent of eight grams of vitamin C (the vitamin C found in a hundred oranges).</p>\n<p>But how do they do against cancer? In the video, <a href=\"https://nutritionfacts.org/video/which-nut-fights-cancer-better/\"><strong>Which Nut Fights Cancer Better?</strong></a>, you can see a <a href=\"http://www.sciencedirect.com/science/article/pii/S0023643808001771\" target=\"_blank\" rel=\"noopener\">graph</a> of human cancer cell proliferation versus increasing concentrations of the ten most common nuts eaten in the United States. If you drip water on these cancer cells as a control, nothing happens. Hazelnuts, pistachios and Brazil nuts don’t do much better. Pine nuts, cashews and macadamias start pulling away from the pack. Almonds appear twice as protective, halving cancer cell growth at only half the dose as pine nuts, cashews, and macadamias. Walnuts, pecans, and peanuts come out as the clear winners, causing a dramatic drop in cancer proliferation at just tiny doses.</p>\n<p>More nuttiness:</p>\n<ul>\n<li><strong><a href=\"https://nutritionfacts.org/video/fighting-inflammation-in-a-nut-shell/\" target=\"_blank\" rel=\"noopener\">Fighting Inflammation in a Nut Shell</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/tree-nuts-or-peanuts-for-breast-cancer-prevention/\" target=\"_blank\" rel=\"noopener\">Tree Nuts or Peanuts for Breast Cancer Prevention?</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/how-do-nuts-prevent-sudden-cardiac-death/\" target=\"_blank\" rel=\"noopener\">How Do Nuts Prevent Sudden Cardiac Death?</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/nuts-and-bolts-of-cholesterol-lowering/\" target=\"_blank\" rel=\"noopener\">Nuts and Bolts of Cholesterol Lowering</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/nuts-and-obesity-the-weight-of-evidence/\" target=\"_blank\" rel=\"noopener\">Nuts and Obesity: The Weight of Evidence</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/nuts-may-help-prevent-death/\" target=\"_blank\" rel=\"noopener\">Nuts May Help Prevent Death</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/walnuts-and-artery-function/\" target=\"_blank\" rel=\"noopener\">Walnuts and Artery Function</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/Four-Nuts-Once-a-Month/\">Four Nuts Once a Month</a></strong></li>\n</ul>\n<p><b>-Michael Greger, M.D.</b></p>\n<p>PS: If you haven’t yet, you can subscribe to my free videos <a href=\"http://www.nutritionfacts.us5.list-manage.com/subscribe?u=c1bae6687e1e6ab175fb56913&amp;id=40f9e497d1\"><span style=\"text-decoration: underline;\"><b>here</b></span></a> and watch my live year-in-review presentations <a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\"><span style=\"text-decoration: underline;\"><b>Uprooting the Leading Causes of Death</b></span></a>, <a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\"><span style=\"text-decoration: underline;\"><b>More Than an Apple a Day</b></span></a>, <a href=\"https://nutritionfacts.org/video/from-table-to-able/\"><span style=\"text-decoration: underline;\"><b>From Table to Able</b></span></a>, and <a href=\"https://nutritionfacts.org/video/food-as-medicine/\"><b>Food as Medicine</b></a>.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/dr-greger-takes-on-mediterranean-diet-in-new-dvd.json
{
  "Title": "Dr. Greger Takes on Mediterranean Diet in New DVD",
  "Url": "https://nutritionfacts.org/blog/dr-greger-takes-on-mediterranean-diet-in-new-dvd/",
  "UpdatedAt": "2015-01-29T13:00:43+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2015/01/Volume-23-Feature-Image.png",
      "https://assets.nutritionfacts.org/2015/01/Volume-23-Feature-Image-300x192.png",
      "https://assets.nutritionfacts.org/2015/01/Volume-23-Feature-Image-312x200.png",
      "https://assets.nutritionfacts.org/2015/01/Volume-23-Feature-Image-1024x655.png",
      "https://assets.nutritionfacts.org/2015/01/Volume-23-Feature-Image-768x491.png",
      "https://assets.nutritionfacts.org/2015/01/Volume-23-Feature-Image-320x204.png"
    ],
    "Attribution": ""
  },
  "Content": {
    "Html": "<p>The Mediterranean Diet is an “in” topic nowadays, in both the medical literature and the lay media. More than 450 papers were published in the medical literature during just the last year alone, more than one a day. As a recent commentary noted “Uncritical laudatory coverage is the common parlance. Specifics are hard to come by: what is it? what is its history? why is it good? Merits are rarely detailed; possible downsides are never mentioned.” I answer these questions and more in a 6-part video series:</p>\n<ul>\n<li value=\"11\">Why Was Heart Disease Rare in the Mediterranean?</li>\n<li value=\"12\">The Mediterranean Diet or a Whole Food Plant-Based Diet?</li>\n<li value=\"13\">PREDIMED: Does Eating Nuts Prevent Strokes?</li>\n<li value=\"14\">Which Parts of the Mediterranean Diet Extended Life?</li>\n<li value=\"15\">Do Flexitarians Live Longer?</li>\n<li value=\"16\">Improving on the Mediterranean Diet</li>\n</ul>\n<p>They are all available right now as a <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"http://www.drgreger.org/downloads\" target=\"_blank\" rel=\"noopener\">video download</a> as part of my new <em>Latest in Clinical Nutrition</em> volume 23 (all proceeds go to this charity). It can also be ordered as a <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"http://www.drgreger.org/dvds\" target=\"_blank\" rel=\"noopener\">physical DVD</a>. The Mediterranean videos are all scheduled to go up on NutritionFacts.org by mid-March, but you can download and watch them <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"http://www.drgreger.org/downloads\" target=\"_blank\" rel=\"noopener\">right now</a>.</p>\n<p>The current batch of videos from <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"https://nutritionfacts.org/blog/dr-greger-addresses-saturated-fat-confusion-in-new-dvd/\" target=\"_blank\" rel=\"noopener\">volume 22</a> on NutritionFacts.org just ran out, so starting next month and running through April, I’ll be rolling out the videos from this new DVD, volume 23. The DVDs give folks the opportunity to sneak-preview videos months ahead of time, watch them all straight through, and share them as gifts, but there is nothing on the DVDs that won’t eventually end up free online here at NutritionFacts.org. If you’d like the works–40+ hours of video–you can get the <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"http://www.drgreger.org/downloads\" target=\"_self\" rel=\"noopener\">complete DVD collection</a>.</p>\n<p>Here’s the list of chapters from the new volume 23 DVD — a preview of what’s to come over the next few months on NutritionFacts.org:</p>\n<ol>\n<li>The Problem with the Paleo Diet Argument</li>\n<li>What Causes Insulin Resistance?</li>\n<li>The Spillover Effect Links Obesity to Diabetes</li>\n<li value=\"4\">Lipotoxicity: How Saturated Fat Raises Blood Sugar</li>\n<li value=\"5\">Plant-Based Workplace Intervention</li>\n<li value=\"6\">The Cilantro Gene</li>\n<li value=\"7\">Reducing Glycotoxin Intake to Prevent Alzheimers</li>\n<li value=\"8\">Optimal Cholesterol Level</li>\n<li value=\"9\">Preventing Ulcerative Colitis with Diet</li>\n<li value=\"10\">Stool pH and Colon Cancer</li>\n<li value=\"11\">Why Was Heart Disease Rare in the Mediterranean?</li>\n<li value=\"12\">The Mediterranean Diet or a Whole Food Plant-Based Diet?</li>\n<li value=\"13\">PREDIMED: Does Eating Nuts Prevent Strokes?</li>\n<li value=\"14\">Which Parts of the Mediterranean Diet Extended Life?</li>\n<li value=\"15\">Do Flexitarians Live Longer?</li>\n<li value=\"16\">Improving on the Mediterranean Diet</li>\n<li value=\"17\">Exercise vs. Drugs for Depression</li>\n<li value=\"18\">Do Antidepressant Drugs Really Work?</li>\n<li value=\"19\">Is Milk Good for Our Bones?</li>\n<li value=\"20\">If White Rice is Linked to Diabetes, What About China?</li>\n<li value=\"21\">Oatmeal Lotion for Chemotherapy-Induced Rash</li>\n<li value=\"22\">Can Oatmeal Help Fatty Liver Disease?</li>\n<li value=\"23\">Nutritional Yeast to Prevent the Common Cold</li>\n<li value=\"24\">ALS (Lou Gehrig’s Disease): Fishing for Answers</li>\n<li value=\"25\">Diet and Amyotrophic Lateral Sclerosis (ALS)</li>\n<li value=\"26\">How Much Fruit Is Too Much?</li>\n</ol>\n<p>Order my new DVD at <strong><a href=\"http://www.drgreger.org/dvds\" target=\"_blank\" rel=\"noopener\">DrGreger.org/dvds</a></strong> or <a href=\"http://smile.amazon.com/Latest-Clinical-Nutrition-Michael-Greger/dp/B00S73ZU48/&amp;tag=httpwwwdrgreg-20\" target=\"_blank\" rel=\"noopener\"><strong>through Amazon</strong></a>. It can also be ordered as a video download at <strong><a href=\"http://www.DrGreger.org/downloads\" target=\"_self\" rel=\"noopener\">DrGreger.org/downloads</a>.</strong><br/>\n </p>\n<div style=\"text-align: left;\"><span style=\"font-size: 18px;\"><strong>DVD Subscription</strong></span></div>\n<p>If you were a regular supporter, you’d already be a Mediterranean diet expert by now, having gotten the new DVD last week! I now come out with DVDs every 9 weeks. If you’d like to automatically receive them before they’re even available to the public, please consider becoming a monthly donor.</p>\n<p>Anyone signing up on the <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"https://nutritionfacts.org/donate/\" target=\"_self\" rel=\"noopener\">donation page</a> to become a $15 monthly contributor will receive the next three DVDs for free (as physical DVDs, downloads, or both–your choice), and anyone signing up as a $25 monthly contributor will get a whole year’s worth of new DVDs. If you’re already signed up and didn’t receive your volume 23 yet, please email Tommasina@NutritionFacts.org and she’ll make everything all better.</p>\n<p>If you’d rather just watch all the videos online as they launch, but would still like to support my work of helping to educate millions about healthy eating, you can make a tax-deductible donation to NutritionFacts.org <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"https://nutritionfacts.org/donate/\" target=\"_blank\" rel=\"noopener\">using a credit card</a>, a <a style=\"color: #339900; font-weight: normal; text-decoration: underline;\" href=\"https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=6SWYJD9SYAZHE\" target=\"_blank\" rel=\"noopener\">direct PayPal link</a>, or by sending a check to NutritionFacts.org 6800 Wisconsin Avenue #1185 Chevy Chase, MD 20815.</p>\n<p>In my next DVD I’ll dig into whether organic fruits and vegetables are safer and healthier enough to justify the extra cost–stay tuned!</p>\n<p><strong>-Michael Greger</strong></p>"
  }
}
