=== MaximePinot/nutritionfactsorg-data/json/schemas/blog.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/blog.schema.json",
    "title": "Blog",
    "description": "A Blog article from nutritionfacts.org",
    "type": "object",
    "properties": {
        "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/blog\\/"
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
        "Author": {
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1,
                    "enum": [
                        "Michael Greger M.D. FACLM",
                        "Brenda Davis and Vesanto Melina",
                        "Joseph Gonzales, R.D.",
                        "Vesanto Melina"
                    ]
                }
            ]
        },
        "CoverImage": {
            "type": "object",
            "properties": {
                "Urls": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "minLength": 1,
                        "format": "uri",
                        "pattern": "^https:\\/\\/assets\\.nutritionfacts\\.org\\/"
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "Attribution": {
                    "type": "string",
                    "minLength": 0
                }
            },
            "required": [
                "Urls",
                "Attribution"
            ],
            "additionalProperties": false
        },
        "Content": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "Title",
        "Url",
        "UpdatedAt",
        "Author",
        "CoverImage",
        "Content"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/chlorohydrin-3-mcpd-in-braggs-liquid-aminos.json
{
  "Title": "Chlorohydrin 3-MCPD in Bragg’s Liquid Aminos",
  "Url": "https://nutritionfacts.org/blog/chlorohydrin-3-mcpd-in-braggs-liquid-aminos/",
  "UpdatedAt": "2025-11-06T13:00:20+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-1024x576.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-720x405.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-1200x675.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-960x540.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-768x432.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-1536x864.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-480x270.jpg",
      "https://assets.nutritionfacts.org/2025/11/2-chlorohydrin-3-mcpd-in-braggs-liquid-aminos-540x304.jpg"
    ],
    "Attribution": ""
  },
  "Content": {
    "Html": "<p>Chlorohydrin contaminates hydrolyzed vegetable protein products and refined oils.</p>\n<p>In 1978, chlorohydrins were <a href=\"https://pubmed.ncbi.nlm.nih.gov/716635/\" target=\"_blank\" rel=\"noopener\">found</a> in protein hydrolysates. What does that mean? Proteins can be broken down into amino acids using a chemical process called hydrolysis, and free amino acids (like glutamate) can have taste-enhancing qualities. That’s how inexpensive soy sauce and seasonings like Bragg’s Liquid Aminos are made. This process requires high heat, high pressure, and hydrochloric acid to break apart the protein. The problem is that when any residual fat is exposed to these conditions, it can form toxic compounds called chlorohydrins, which are toxic at least to mice and rats.</p>\n<p>Chlorohydrins like 3-MCPD are <a href=\"https://pubmed.ncbi.nlm.nih.gov/25830907/\" target=\"_blank\" rel=\"noopener\">considered</a> “a worldwide problem of food chemistry,” but no long-term clinical studies on people have been reported to date. The concern is about the detrimental effects on the kidneys and fertility. In fact, there was a time 3-MCPD was <a href=\"https://pubmed.ncbi.nlm.nih.gov/21351250/\" target=\"_blank\" rel=\"noopener\">considered</a> as a potential male contraceptive because it could so affect sperm production, but research funding was withdrawn after “unacceptable side effects [were] observed in primates.” Researchers <a href=\"https://pubmed.ncbi.nlm.nih.gov/418534/\" target=\"_blank\" rel=\"noopener\">found</a> flaccid testes in rats, which is what they were going for, but it caused neurological scars in monkeys.</p>\n<p>What <a href=\"https://pubmed.ncbi.nlm.nih.gov/15093263/\" target=\"_blank\" rel=\"noopener\">do</a> you do when there are no studies in humans? How do you set some kind of safety factor? It isn’t easy, but you can take the lowest observed adverse effect level (LOAEL) in animal studies, which, <a href=\"https://pubmed.ncbi.nlm.nih.gov/32625654/\" target=\"_blank\" rel=\"noopener\">in this case</a>, was kidney damage, <a href=\"https://pubmed.ncbi.nlm.nih.gov/15093263/\" target=\"_blank\" rel=\"noopener\">add</a> in some kind of fudge factor, and then arrive at an estimated tolerable daily intake (TDI). For 3-MCPD, this means that high-level consumers of soy sauce may exceed the limit. This was <a href=\"https://ilsi.eu/publication/3-mcpd-esters-in-food-products-summary-report/\" target=\"_blank\" rel=\"noopener\">based</a> on extraordinarily high contamination levels, though. Since that study, Europe <a href=\"https://pubmed.ncbi.nlm.nih.gov/21351250/\" target=\"_blank\" rel=\"noopener\">introduced</a> a regulatory limit of 20 parts per billion (ppb) of 3-MCPD in hydrolyzed vegetable protein products like liquid aminos and soy sauce. The U.S. standards <a href=\"https://www.fda.gov/regulatory-information/search-fda-guidance-documents/cpg-sec-500500-guidance-levels-3-mcpd-3-chloro-12-propanediol-acid-hydrolyzed-protein-and-asian\" target=\"_blank\" rel=\"noopener\">are</a> much laxer, though, setting a “guidance level” of up to 50 times more, 1,000 parts per billion.</p>\n<p>I called Bragg’s to see where it fell, and the good news is that it is doing an independent, third-party analysis of its liquid aminos for 3-MCPD. The bad news is that, despite my pleas that it be fully transparent, Bragg’s wouldn’t let me share the results with you. I have seen them, though, but I’m only allowed to confirm they comfortably meet the U.S. standards but fail to meet the European standards.</p>\n<p>This is just the start of the 3-MCPD story, though. A study in Italy <a href=\"https://pubmed.ncbi.nlm.nih.gov/25862474/\" target=\"_blank\" rel=\"noopener\">tested</a> individuals’ urine for 3-MCPD or its metabolites, and 100% of the people turned up positive, confirming that it’s “a widespread food contaminant.” But 100% of people aren’t consuming soy sauce or liquid aminos every day. Remember, the chemical <a href=\"https://pubmed.ncbi.nlm.nih.gov/25830907/\" target=\"_blank\" rel=\"noopener\">results</a> from a reaction with residual vegetable oil. When vegetable oil itself is <a href=\"https://ilsi.eu/publication/3-mcpd-esters-in-food-products-summary-report/\" target=\"_blank\" rel=\"noopener\">refined</a>, when it’s deodorized and bleached, those conditions also lead to the formation of 3-MCPD.</p>\n<p>Indeed, we’ve known for years that various foods are <a href=\"https://www.researchgate.net/publication/284193508_Esters_of_3-chloropropane-12-diol_in_foodstuffs\" target=\"_blank\" rel=\"noopener\">contaminated</a>. In what kinds of foods <a href=\"https://www.bfr.bund.de/en/service/frequently-asked-questions/topic/frequently-asked-questions-regarding-the-contamination-of-foods-with-3-mcpd-2-mcpd-and-glycidyl-fatty-acid-esters/\" target=\"_blank\" rel=\"noopener\">have</a> these kinds of chemicals been detected? Well, if they’re in oils and fats, then they’re in greasy foods made from them: margarine, baked goods, pastries, deep-fried foods, fatty snacks like potato and corn chips, as well as infant formula.</p>\n<p>The U.S. Food and Drug Administration’s limit for soy sauce <a href=\"https://www.researchgate.net/publication/284193508_Esters_of_3-chloropropane-12-diol_in_foodstuffs\" target=\"_blank\" rel=\"noopener\">is</a> 1,000 ppb, but donuts can have more than 1,200 ppb, salami more than 1,500 ppb, ham nearly 3,000 ppb, and French fries in excess of 6,000 ppb, as seen here and at 4:03 in my video <strong><a href=\"https://nutritionfacts.org/video/the-side-effects-of-3-mcpd-in-braggs-liquid-aminos/\" target=\"_blank\" rel=\"noopener\">The Side Effects of 3-MCPD in Bragg’s Liquid Aminos</a></strong>.</p>\n<p><img decoding=\"async\" class=\"aligncenter size-full wp-image-116843\" src=\"https://assets.nutritionfacts.org/2025/11/4-03.png\" alt=\"\" width=\"1920\" height=\"1080\" srcset=\"https://assets.nutritionfacts.org/2025/11/4-03.png 1920w, https://assets.nutritionfacts.org/2025/11/4-03-960x540.png 960w, https://assets.nutritionfacts.org/2025/11/4-03-1024x576.png 1024w, https://assets.nutritionfacts.org/2025/11/4-03-768x432.png 768w, https://assets.nutritionfacts.org/2025/11/4-03-1536x864.png 1536w, https://assets.nutritionfacts.org/2025/11/4-03-480x270.png 480w, https://assets.nutritionfacts.org/2025/11/4-03-1200x675.png 1200w, https://assets.nutritionfacts.org/2025/11/4-03-720x405.png 720w, https://assets.nutritionfacts.org/2025/11/4-03-540x304.png 540w\" sizes=\"(max-width: 1920px) 100vw, 1920px\"/></p>\n<p>Most of us don’t <a href=\"https://pubmed.ncbi.nlm.nih.gov/26161901/\" target=\"_blank\" rel=\"noopener\">have</a> to worry about this problem, unless we’re consumers of fried food. Someone <a href=\"https://www.researchgate.net/publication/284193508_Esters_of_3-chloropropane-12-diol_in_foodstuffs\" target=\"_blank\" rel=\"noopener\">weighing</a> about 150 pounds, for example, who eats 116 grams of donuts, would exceed the European Food Safety Authority’s TDI, even if those donuts were the person’s only source of exposure. That’s about two donuts, but the same limit-blowing amount of 3-MCPD could be found in only five French fries.</p>\n<p><strong>Doctor’s Note</strong></p>\n<p>Believe me, I pleaded with the Bragg’s folks over and over. It’s curious to me that Bragg’s allowed me to talk about where its level of 3-MCPD fell compared to the standards but not say the number itself. At least it’s doing third-party testing.</p>\n<p>Learn more about this topic in my video <strong><a href=\"https://nutritionfacts.org/video/3-mcpd-in-refined-cooking-oils/\" target=\"_blank\" rel=\"noopener\">3-MCPD in Refined Cooking Oils</a></strong>.</p>\n<p>You can also check out<strong><a href=\"https://nutritionfacts.org/video/friday-favorites-the-side-effects-of-3-mcpd-in-braggs-liquid-aminos-and-refined-cooking-oils/\" target=\"_blank\" rel=\"noopener\"> Friday Favorites: The Side Effects of 3-MCPD in Bragg’s Liquid Aminos and Refined Cooking Oils</a></strong>.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/gmos-safe-case-bt-corn.json
{
  "Title": "Is Insecticidal GMO Corn Safe?",
  "Url": "https://nutritionfacts.org/blog/gmos-safe-case-bt-corn/",
  "UpdatedAt": "2016-06-28T12:00:38+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2016/06/NF-June28-320x139.jpeg",
      "https://assets.nutritionfacts.org/2016/06/NF-June28.jpeg",
      "https://assets.nutritionfacts.org/2016/06/NF-June28-300x130.jpeg",
      "https://assets.nutritionfacts.org/2016/06/NF-June28-768x334.jpeg",
      "https://assets.nutritionfacts.org/2016/06/NF-June28-460x200.jpeg",
      "https://assets.nutritionfacts.org/2016/06/NF-June28-1024x445.jpeg"
    ],
    "Attribution": "Image Credit: Jen Wilton / Flickr. This image has been modified."
  },
  "Content": {
    "Html": "<p>Recently, the prominent science journal <em>Nature</em> <a href=\"http://www.nature.com/news/plan-for-the-future-1.12896\" target=\"_blank\" rel=\"noopener\">editorialized</a> that we are now swimming in information about genetically modified crops, but that much of the information is wrong—on both sides of the debate. “But a lot of this incorrect information is sophisticated, backed by legitimate-sounding research and written with certitude,” <a href=\"http://www.nature.com/news/plan-for-the-future-1.12896\">add</a><a href=\"http://www.nature.com/news/plan-for-the-future-1.12896\" target=\"_blank\" rel=\"noopener\">ing</a> that with GMOs, “a good gauge of a statement’s fallacy is the conviction with which it is delivered.”</p>\n<p>To many in the scientific community, GMO concerns are dismissed as one big conspiracy theory. In fact, one item in a psychological test of belief in conspiracy theories <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/23818886\" target=\"_blank\" rel=\"noopener\">asked</a> people if they thought food companies would have the audacity to be dishonest about genetically modified food. The study concluded that many people were cynical and skeptical with regard to advertising tricks, as well as the tactics of organizations like banks and alcohol, drug, and tobacco companies. That doesn’t sound like conspiracy theory to me; that sounds like business as usual.</p>\n<p>We must remember there is a long <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/23308036\" target=\"_blank\" rel=\"noopener\">legacy</a> of scientific misconduct. Throw in a multi-billion dollar industry, and one can imagine how <a href=\"http://www.ifpri.org/publication/measuring-economic-impacts-transgenic-crops-developing-agriculture-during-first-decade\" target=\"_blank\" rel=\"noopener\">hard it is to get to the truth of the matter</a>. There are social, environmental, economic, food security, and biodiversity arguments both pro and con about GMOs, but those are outside my area of expertise. I’m going to stick to food safety. And as a physician, I’m a very limited veterinarian—I only know one species (us!). So, I will skip the lab animal data and ask instead: What human data do we have about GMO safety?</p>\n<p>One study “<a href=\"http://www.ncbi.nlm.nih.gov/pubmed/23936105\">confirm</a><a href=\"http://www.ncbi.nlm.nih.gov/pubmed/23936105\">ed</a>” that DNA from genetically modified crops can be transferred into humans who eat them, but that’s not what the study found, just that plant DNA in general may be found in the human bloodstream, with no stipulations of harm (See <strong><a title=\"Are GMOs Safe? The Case of Bt Corn\" href=\"https://nutritionfacts.org/video/are-gmos-safe-the-case-of-bt-corn/\" rel=\"bookmark\">Are GMOs Safe? The Case of Bt Corn</a></strong>).</p>\n<p>Another study, however, did <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/21338670\" target=\"_blank\" rel=\"noopener\">find</a> a GMO crop protein in people. The “toxin” was detected in 93 percent of blood samples of pregnant women, 80 percent of umbilical cord blood samples, and 69 percent of samples from non-pregnant women. The toxin they’re talking about is an insecticidal protein produced by Bt bacteria whose gene was inserted into the corn’s DNA to create so-called Bt-corn, which has been incorporated into animal feed. If it’s mainly in animal feed, how did it get into the bodies of women? They suggest it may be through exposure to contaminated meat.</p>\n<p>Of course, why get GMO’s second-hand when you can get them directly? The next great frontier is <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22361646\" target=\"_blank\" rel=\"noopener\">transgenic farm animals</a>. A <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/21276930\" target=\"_blank\" rel=\"noopener\">genetically modified salmon</a> was first to vie for a spot at the dinner table. And then in 2010, transgenic cows, sheep, goats and pigs were <a href=\"http://www.nature.com/news/politics-holds-back-animal-engineers-1.11596?WT.ec_id=NATUREjobs-20121018\" target=\"_blank\" rel=\"noopener\">created</a>, genetically modified for increased muscle mass, based on the so-called <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/9139826\" target=\"_blank\" rel=\"noopener\">mighty mouse model</a>. Frankenfurters!</p>\n<p>But back to children of the corn and their mothers. When they say it’s a toxin, it’s a toxin to corn worms, not necessarily to people. In fact I couldn’t find any data linking BT toxin to human harm, which is a good thing since it’s considered one of the few pesticides considered so non-toxic that it’s sprayed on organic fruits and vegetables.</p>\n<p>For more on on the public health implications of genetically modified crops, see:</p>\n<ul>\n<li><strong><a href=\"https://nutritionfacts.org/video/are-gmos-safe-the-case-of-roundup-ready-soy/\" target=\"_blank\" rel=\"noopener\">Are GMOs Safe? The Case of Roundup Ready Soy</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/is-monsantos-roundup-pesticide-glyphosate-safe/\" target=\"_blank\" rel=\"noopener\">Is Monsanto’s Roundup Pesticide Glyphosate Safe?</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/gmo-soy-and-breast-cancer/\" target=\"_blank\" rel=\"noopener\">GMO Soy and Breast Cancer</a></strong></li>\n</ul>\n<p>I did a similar “controversial issue” video series on gluten. See:</p>\n<ul>\n<li><strong><a href=\"https://nutritionfacts.org/video/is-gluten-sensitivity-real/\">Is Gluten Sensitivity Real?</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/gluten-free-diets-separating-the-wheat-from-the-chat/\">Gluten-Free Diets: Separating the Wheat from the Chat</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/how-to-diagnose-gluten-intolerance/\">How to Diagnose Gluten Intolerance</a></strong></li>\n</ul>\n<p>For those interested in the genetic engineering of livestock, I published a few papers myself on the topic:</p>\n<ul>\n<li><a href=\"http://www.drgreger.org/Greger_2011_CAB.pdf\">Centre for Agriculture and Biosciences (CAB) Reviews 6(41):1-6.</a></li>\n<li><a href=\"http://www.springerlink.com/content/p811p18540937037/?p=56600355cd164d5590ad163e1ae6430b&amp;pi=1\">Journal of Agricultural and Environmental Ethics 24(5):451-472.</a></li>\n<li><a href=\"http://www.journalofanimalscience.org/content/88/2/811.full\"> Journal of Animal Science 88(2):811-4.</a></li>\n</ul>\n<div>\n<p>In health,<b><br/>Michael Greger, M.D.</b></p>\n<p>PS: If you haven’t yet, you can subscribe to my free videos <a href=\"http://www.nutritionfacts.us5.list-manage.com/subscribe?u=c1bae6687e1e6ab175fb56913&amp;id=40f9e497d1\"><u>here</u></a> and watch my live year-in-review presentations <a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\"><u><b>Uprooting the Leading Causes of Death</b></u></a>,<b> </b><a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\"><u><b>More Than an Apple a Day</b></u></a>,<b> </b><a href=\"https://nutritionfacts.org/video/from-table-to-able/\"><u><b>From Table to Able</b></u></a>, and<b> </b><a href=\"https://nutritionfacts.org/video/food-as-medicine/\"><u><b>Food as Medicine</b></u></a>.</p>\n</div>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/how-to-get-our-kids-to-eat-their-vegetables.json
{
  "Title": "How to Get Our Kids to Eat Their Vegetables",
  "Url": "https://nutritionfacts.org/blog/how-to-get-our-kids-to-eat-their-vegetables/",
  "UpdatedAt": "2014-06-17T12:00:36+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home-460x200.jpg",
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home-800x347.jpg",
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home-1024x444.jpg",
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home-768x333.jpg",
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home-320x138.jpg",
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home.jpg",
      "https://assets.nutritionfacts.org/2014/06/NF-June17-Tricks-to-Get-Kids-to-Eat-Healthier-at-Home-300x130.jpg"
    ],
    "Attribution": "Image Credit: U.S. Department of Agriculture / Flickr.  This image has been modified."
  },
  "Content": {
    "Html": "<p>When researchers offered kids broccoli or a chocolate bar, which do you think they <a href=\"http://connection.ebscohost.com/c/articles/77547340/p136-do-spokes-characters-improve-consumption-vegetables-among-children\" target=\"_blank\">picked</a>? Four out of five picked the chocolate (though how proud are the parents of the one in five kids that chose the broccoli?!).</p>\n<p>But what if we put an Elmo sticker on the broccoli? When an Elmo sticker was placed on the broccoli, it was half and half. Fifty percent chose the broccoli.</p>\n<p>It works in schools, too. A picture of SpongeBob saying, “Got beans?” and 37% more boys and 17% more girls chose green beans. One little sign and kids were eating significantly more vegetables.</p>\n<p>We saw how we should <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22391143\" target=\"_blank\">cut up</a> (or cut out) cookies to minimize consumption in my video <strong><a href=\"https://nutritionfacts.org/video/tricks-to-get-kids-to-eat-healthier-at-school/\" target=\"_blank\" data-ls-seen=\"1\">Tricks to Get Kids to Eat Healthier at School</a></strong>. How should we cut up vegetables to <em>maximize</em> consumption? Which do you think 9 to 12 year olds <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22796947\" target=\"_blank\">ate</a> more of, whole slices, sticks or stars? And do they like them bigger, or smaller? The results were strikingly clear. Turns out “Shape was very influential; children clearly preferred having their vegetables cut.” Stars were liked the most. What about whole slices versus sticks? No difference. It turns out that size only mattered for the whole chunk: the ordinary size was preferred to the miniature versions.</p>\n<p>If they’re still not biting, we can <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22027046\" target=\"_blank\">apply</a> the same trick I use to get our dog to eat stuff she doesn’t like: dip it in peanut butter. “Pairing vegetables with peanut butter may successfully increase intake, even in vegetable-resistant children.” <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22741167\" target=\"_blank\">Offering</a> a salad dressing dip may help, too.</p>\n<p>Then there’s always the hidden vegetables strategy.  In one <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/21775554\" target=\"_blank\">study</a>, “broccoli, cauliflower, tomatoes, squash, and zucchini were covertly added to familiar entrees so that the appearance, flavor, and texture of the original recipes were maintained,” like pureeing vegetables into a pasta sauce, and families weren’t any wiser. Covertly incorporating vegetables into foods can “have a beneficial effect on children’s vegetable intake, but it should not be the only way that vegetables are served to children.”  Since the appetite for an initially unappetizing vegetable can be increased through repeated exposure, it is important to use several strategies to ensure that children experience different forms of vegetables, especially whole vegetables, because they’re not always going to be at home.</p>\n<p>Worse comes to worst, public health advocates can make a video game. There’s a public/private partnership, “<a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22771184\" target=\"_blank\" data-ls-seen=\"1\">The Quest to Lava Mountain</a>,” where you can apparently harvest kale and gain “knowledge about the health benefits of eating healthy foods such as fruits, vegetables, and whole-grain foods” as well as the detrimental effects of eating junk. Where were the kale video games when I was growing up?</p>\n<p>What may be the best way, though, to get kids to eat more fruits and vegetables? One <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/20849895\" target=\"_blank\" data-ls-seen=\"1\">study</a>, featured in my video <a href=\"https://nutritionfacts.org/video/tricks-to-get-kids-to-eat-healthier-at-home/\" target=\"_blank\"><strong>Tricks to Get Kids to Eat Healthier at Home</strong></a>, looked at all sorts of parenting styles—should we pressure them or should we lay off? What was the most important factor? The most important predictor of children’s fruit consumption was… <em>the parent</em>‘<em>s consumption</em>. That was pretty much the case with vegetables, too. If we want our kids to eat healthy, we have to model healthy behavior. The researchers concluded that in order to try to increase children’s fruit and vegetable consumption, parents should be guided to improve their own diets first.</p>\n<p>For a smattering of other videos on children’s health, check out:</p>\n<ul>\n<li><strong><a title=\"Video: Nerves of Mercury\" href=\"https://nutritionfacts.org/video/nerves-of-mercury/\" target=\"_blank\" data-ls-seen=\"1\">Nerves of Mercury</a></strong></li>\n<li><strong><a title=\"Video: Doctors’ Nutritional Ignorance\" href=\"https://nutritionfacts.org/video/doctors-nutritional-ignorance/\" target=\"_blank\" data-ls-seen=\"1\">Doctors’ Nutritional Ignorance</a></strong></li>\n<li><strong><a title=\"Video: Protein, Puberty, and Pollutants\" href=\"https://nutritionfacts.org/video/protein-puberty-and-pollutants/\" target=\"_blank\" data-ls-seen=\"1\">Protein, Puberty, and Pollutants</a></strong></li>\n<li><strong><a title=\"Video: How Fast Can Children Detoxify from PCBs?\" href=\"https://nutritionfacts.org/video/how-fast-can-children-detoxify-from-pcbs/\" target=\"_blank\" data-ls-seen=\"1\">How Fast Can Children Detoxify from PCBs?</a></strong></li>\n<li><strong><a title=\"Video: Does a Drink Of Water Make Children Smarter?\" href=\"https://nutritionfacts.org/video/does-a-drink-of-water-make-children-smarter/\" target=\"_blank\" data-ls-seen=\"1\">Does a Drink of Water Make Children Smarter?</a></strong></li>\n<li><strong><a title=\"Video: Are Cats or Dogs More Protective For Children’s Health?\" href=\"https://nutritionfacts.org/video/are-cats-or-dogs-more-protective-for-childrens-health/\" target=\"_blank\" data-ls-seen=\"1\">Are Cats or Dogs More Protective For Children’s Health?</a></strong></li>\n</ul>\n<p>I cover grown-ups in <strong><a href=\"https://nutritionfacts.org/video/tricks-to-get-adults-to-eat-healthier/\" target=\"_blank\" data-ls-seen=\"1\">Tricks to Get Adults to Eat Healthier</a></strong>.<strong></strong></p>\n<p><strong>-Michael Greger, M.D.</strong></p>\n<p>PS: If you haven’t yet, you can subscribe to my videos for free by <a href=\"https://nutritionfacts.us5.list-manage.com/subscribe?u=c1bae6687e1e6ab175fb56913&amp;id=40f9e497d1\" target=\"_blank\"><strong>clicking here</strong></a> and watch my full 2012 – 2015 presentations <strong><a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\" target=\"_blank\">Uprooting the Leading Causes of Death</a></strong><a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\" target=\"_blank\"></a>, <strong><a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\">More than an Apple a Day</a></strong>, <strong><a href=\"https://nutritionfacts.org/video/from-table-to-able/\">From Table to Able</a></strong>, and <strong><a href=\"https://nutritionfacts.org/video/food-as-medicine/\">Food as Medicine</a></strong>.</p>"
  }
}
