=== MaximePinot/nutritionfactsorg-data/json/schemas/blog.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/blog.schema.json",
    "title": "Blog",
    "description": "A Blog article from nutritionfacts.org",
    "type": "object",
    "properties": {
        "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/blog\\/"
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
        "Author": {
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1,
                    "enum": [
                        "Michael Greger M.D. FACLM",
                        "Brenda Davis and Vesanto Melina",
                        "Joseph Gonzales, R.D.",
                        "Vesanto Melina"
                    ]
                }
            ]
        },
        "CoverImage": {
            "type": "object",
            "properties": {
                "Urls": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "minLength": 1,
                        "format": "uri",
                        "pattern": "^https:\\/\\/assets\\.nutritionfacts\\.org\\/"
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "Attribution": {
                    "type": "string",
                    "minLength": 0
                }
            },
            "required": [
                "Urls",
                "Attribution"
            ],
            "additionalProperties": false
        },
        "Content": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "Title",
        "Url",
        "UpdatedAt",
        "Author",
        "CoverImage",
        "Content"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/plant-based-is-not-the-same-as-vegetarianism.json
{
  "Title": "Plant-Based Is Not the Same as Vegetarianism",
  "Url": "https://nutritionfacts.org/blog/plant-based-is-not-the-same-as-vegetarianism/",
  "UpdatedAt": "2018-02-01T13:00:37+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-960x540.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-768x432.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-1024x576.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-720x405.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-540x304.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-355x200.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-928x522.jpeg",
      "https://assets.nutritionfacts.org/2018/02/Optimal-Diet-Just-Give-it-To-Me-Straight-1-1200x675.jpeg"
    ],
    "Attribution": "Image Credit: Kristina DeMuth"
  },
  "Content": {
    "Html": "<p>Referring to heart disease, <a href=\"http://www.dresselstyn.com/site/about/about-dr-esselstyn/\">Dr. Caldwell B. Esselstyn, Jr., MD</a> asks, “Why is there reticence to provide the public with guidelines that will spare them this disease or its progression?” in an article <a href=\"http://www.ajconline.org/article/S0002-9149(98)00714-0/fulltext\">published</a> in <em>The American Journal of Cardiology</em>. “The National Research Council position was that a dietary fat recommendation lower than 30% would be too frustrating for those attempting to achieve a significant reduction. Although it is uncertain to what extent people will adopt the advice, it is nevertheless scientifically and ethically imperative to inform the public what constitutes an optimal diet. We must tell the public the truth about what is best for their health, and let them decide their degree of compliance,” he asserts.</p>\n<p>My video <a href=\"https://nutritionfacts.org/video/optimal-diet-just-give-it-to-me-straight-doc/\"><strong>Optimal Diet: Just Give It to Me Straight, Doc</strong></a> describes how Dr. Esselstyn challenged an expert panel to answer these questions from patients: “I’ll do anything, but I never want to have heart disease” and “I’ve had a heart attack, and I never want another.” Answers ranged from having them “eat beans, beans, and more beans” to it’s “time for the public to embrace a plant-based diet.”</p>\n<p>The recommended plant-based diet is not the same as vegetarianism. Vegetarians often consume all sorts of less-than-healthful foods, such as oils, margarine, dairy products, and eggs. Vegans do, too, for that matter. “This new paradigm is exclusively plant-based nutrition,” Dr. Esselstyn explains. In other words, it consists only of whole plant foods. Why exclusively? Because, as <a href=\"http://www.ajconline.org/article/S0002-9149(98)00718-8/pdf\">reported</a> in the <a href=\"http://www.cornell.edu/video/playlist/the-china-project-studying-the-link-between-diet-and-disease\">Cornell China Study</a>, there does not appear to be “a threshold beyond which further benefits do not accrue with increasing proportions of plant-based foods in the diet.” It appears the more plant-based foods and the fewer animal-based foods, the better.</p>\n<p>In a separate paper <a href=\"http://www.ajconline.org/article/S0002-9149(98)00715-2/pdf\">published</a> in <em>The American Journal of Cardiology</em>, Dr. Esselstyn acknowledges that he is “acutely aware of the castigation that accompanies recommending a plant-based diet—namely that the recommendation will be met with skepticism and hostility on the part of the general public”—though less so these days as millions jump on the plant-based wagon. But that hostility is “peculiar,” Dr. Esselstyn continues, “because many cultures sustain themselves with such a diet, enjoying its taste, texture, and variety, as well as its health-promoting qualities. However, dietary preference is deeply personal, and one can easily be offended. Nevertheless, the public has a right to know the truth as understood by experts in nutritive biology about what constitutes the safest and healthiest diet.”</p>\n<p>I couldn’t have said it better. The public has a right to know the truth.</p>\n<p>“Some criticize this exclusively plant-based diet as extreme or draconian. Webster’s dictionary defines draconian as ‘inhumanly cruel.’ A closer look reveals that ‘extreme’ or ‘inhumanly cruel’ describes not plant-based nutrition, but the consequences of our present Western diet,” Dr. Esselstyn writes, adding that having a breastbone sawed in half for bypass surgery or a stroke that renders one an invalid unable to speak “can be construed as extreme, and having a breast, prostate, colon, or rectum removed to treat cancer may seem inhumanly cruel.” <em>That’s</em> extreme.</p>\n<p>Eating a bean burrito is easy.</p>\n<hr/>\n<p>So what should the cholesterol guidelines be for the prevention of our number-one killer? The answer to that question can be found in my video <a href=\"https://nutritionfacts.org/video/everything-in-moderation-even-heart-disease/\"><strong>Everything in Moderation? Even Heart Disease?</strong></a><strong>. </strong>You can also learn at what age this information applies to you and your loved ones in my videos <a href=\"https://nutritionfacts.org/video/how-not-to-die-from-heart-disease/\"><strong>How Not to Die from Heart Disease</strong></a> and <a href=\"https://nutritionfacts.org/video/heart-disease-may-start-in-the-womb/\"><strong>Heart Disease May Start in the Womb</strong></a>.</p>\n<p>If you know someone who already has heart disease, be sure to also watch my video <a href=\"https://nutritionfacts.org/video/eliminating-90-of-heart-disease-risk/\"><strong>Eliminating 90% of Heart Disease Risk</strong></a>, in which I compare the effectiveness of pharmacological therapies against those of a plant-based diet.</p>\n<p>For more information on lifestyle approaches to chronic disease, which can sometimes be not only cheaper and safer but also more effective than pharmacological or surgical approaches, take a look at some of my other videos:</p>\n<ul>\n<li><a href=\"https://nutritionfacts.org/video/lifestyle-medicine-treating-the-causes-of-disease/\"><strong>Lifestyle Medicine: Treating the Causes of Disease</strong></a></li>\n<li><a href=\"https://nutritionfacts.org/video/convincing-doctors-to-embrace-lifestyle-medicine/\"><strong>Convincing Doctors to Embrace Lifestyle Medicine</strong></a></li>\n<li><a href=\"https://nutritionfacts.org/video/what-diet-should-physicians-recommend/\"><strong>What Diet Should Physicians Recommend?</strong></a></li>\n<li><a href=\"https://nutritionfacts.org/video/The-Actual-Benefit-of-Diet-vs-Drugs/\"><strong>The Actual Benefit of Diet vs. Drugs</strong></a></li>\n<li><a href=\"https://nutritionfacts.org/video/Why-Prevention-is-Worth-a-Ton-of-Cure/\"><strong>Why Prevention Is Worth a Ton of Cure</strong></a></li>\n<li><a href=\"https://nutritionfacts.org/video/physicians-may-be-missing-their-most-important-tool/\"><strong>Physicians May Be Missing Their Most Important Tool</strong></a></li>\n</ul>\n<p>In health,</p>\n<p><b>Michael Greger, M.D.</b></p>\n<p>PS: If you haven’t yet, you can subscribe to my free videos <a href=\"https://nutritionfacts.org/subscribe/\"><u><b>here</b></u></a><b> </b>and watch my live, year-in-review presentations:</p>\n<ul>\n<li>2012: <a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\"><u><b>Uprooting the Leading Causes of Death</b></u></a></li>\n<li>2013: <a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\"><u><b>More Than an Apple a Day</b></u></a></li>\n<li>2014: <a href=\"https://nutritionfacts.org/video/from-table-to-able/\"><u><b>From Table to Able: Combating Disabling Diseases with Food</b></u></a></li>\n<li>2015: <a href=\"https://nutritionfacts.org/video/food-as-medicine/\"><u><b>Food as Medicine: Preventing and Treating the Most Dreaded Diseases with Diet</b></u></a></li>\n<li>2016: <a href=\"https://nutritionfacts.org/video/how-not-to-die/\"><u><b>How Not To Die: The Role of Diet in Preventing, Arresting, and Reversing Our Top 15 Killers</b></u></a></li>\n</ul>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/overdosing-on-poppy-seeds.json
{
  "Title": "Overdosing on Poppy Seeds",
  "Url": "https://nutritionfacts.org/blog/overdosing-on-poppy-seeds/",
  "UpdatedAt": "2014-09-11T12:00:42+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many-768x333.jpg",
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many-320x139.jpg",
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many.jpg",
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many-300x130.jpg",
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many-460x200.jpg",
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many-800x347.jpg",
      "https://assets.nutritionfacts.org/2014/09/NF-Sep9-How-Many-Poppy-Seeds-Are-Too-Many-1024x445.jpg"
    ],
    "Attribution": "Image Credit: Kirsten Loza / Flickr.  This image has been modified."
  },
  "Content": {
    "Html": "<p>The opium poppy used to make heroin is the same opium poppy used to make muffins and bagels. Does this mean that poppy seed muffin we may have had for breakfast contained a powerful narcotic? The idea that poppy seeds could serve as the source of appreciable amounts of codeine/morphine was not <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/3979930\" target=\"_blank\" rel=\"noopener\">given</a> much credence despite the existence of an old European custom recommending a poppy-seed-filled pacifier to quiet a noisy baby. It wasn’t given much credence, that is, <em>until</em> a mother <a href=\"http://www.bfr.bund.de/cm/364/cases_of_poisoning_reported_by_physicians_2005.pdf\" target=\"_blank\" rel=\"noopener\">tried</a> giving her six-month-old some strained milk she had boiled some poppy seeds in with the very best intentions of helping the child sleep better. It worked a little too well, culminating in respiratory arrest. Now we have <a href=\"http://www.bfr.bund.de/en/press_information/2005/12/poppy_seed_for_baking_is_not_a_soporific_for_infants-6282.html\" target=\"_blank\" rel=\"noopener\">governmental warnings</a> that such a practice is not a good idea.</p>\n<p>The cases aren’t limited to children. Evidently if we <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/19901868\" target=\"_blank\" rel=\"noopener\">eat</a> spaghetti with a half cup of poppy seeds on top, it can make adults a little loopy as well.</p>\n<p>So what’s the upper limit of poppy seed consumption that’s probably safe? A study profiled in my video, <a href=\"https://nutritionfacts.org/video/how-many-poppy-seeds-are-too-many/\" target=\"_blank\" rel=\"noopener\"><strong>How Many Poppy Seeds is Too Many?</strong></a>, suggests about one teaspoon for every seven pounds of body weight. That means that someone weighing about 150 pounds (70 kilograms) should probably eat no more than seven tablespoons of raw poppy seeds at a time.</p>\n<p>Cooking may wipe out half of the morphine and codeine, though, so that gives us some more leeway when baking. Soaking the seeds for five minutes first and then discarding the water before adding them to our recipe can eliminate another half if we’re making some poppy seed filled pastry or something for kids. Otherwise, though, there shouldn’t be any risk at usual levels of intake—unless you’re going in for a drug test, in which case you may want to <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/19901868\" target=\"_blank\" rel=\"noopener\">avoid</a> poppy seeds altogether.</p>\n<p>To learn more about not overdoing healthy foods check out these videos:</p>\n<ul>\n<li><strong><a href=\"https://nutritionfacts.org/video/overdosing-on-greens/\" target=\"_blank\" rel=\"noopener\">Overdosing on Greens</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/how-much-broccoli-is-too-much/\" target=\"_blank\" rel=\"noopener\">How Much Broccoli Is Too Much?</a></strong></li>\n<li><strong><a href=\"https://nutritionfacts.org/video/how-much-soy-is-too-much/\" target=\"_blank\" rel=\"noopener\">How Much Soy Is Too Much?</a></strong></li>\n</ul>\n<p><strong>-Michael Greger, M.D.</strong></p>\n<p>PS: If you haven’t yet, you can subscribe to my videos for free by <a href=\"https://nutritionfacts.us5.list-manage.com/subscribe?u=c1bae6687e1e6ab175fb56913&amp;id=40f9e497d1\" target=\"_blank\" rel=\"noopener\"><strong>clicking here</strong></a> and watch my full 2012 – 2015 presentations <strong><a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\" target=\"_blank\" rel=\"noopener\">Uprooting the Leading Causes of Death</a></strong>, <strong><a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\">More than an Apple a Day</a></strong>, <strong><a href=\"https://nutritionfacts.org/video/from-table-to-able/\">From Table to Able</a></strong>, and <strong><a href=\"https://nutritionfacts.org/video/food-as-medicine/\">Food as Medicine</a></strong>.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/blog/berries-to-prevent-muscle-soreness.json
{
  "Title": "Berries to Prevent Muscle Soreness",
  "Url": "https://nutritionfacts.org/blog/berries-to-prevent-muscle-soreness/",
  "UpdatedAt": "2014-05-08T12:00:27+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "CoverImage": {
    "Urls": [
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries.jpg",
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries-300x130.jpg",
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries-460x200.jpg",
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries-800x347.jpg",
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries-1024x444.jpg",
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries-768x333.jpg",
      "https://assets.nutritionfacts.org/2014/05/NF-May6-Reducing-Muscle-Soreness-with-Berries-320x139.jpg"
    ],
    "Attribution": "Image Credit: Gavin St. Ours / Flickr.  This image has been modified."
  },
  "Content": {
    "Html": "<p>The burning sensation during strenuous exercise may be related to the build-up of lactic acid in our muscles (see <a href=\"https://nutritionfacts.org/video/reducing-muscle-fatigue-with-citrus/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\"><strong>Reducing Muscle Fatigue with Citrus</strong></a>), but that’s different than the delayed onset muscle soreness that occurs in the days following a bout of extreme physical activity. This post-exercise soreness is <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/2072832\" target=\"_blank\" rel=\"noopener\">thought</a> to be due to inflammation caused by muscle cell damage (little micro-tears in the muscle).</p>\n<p>If it’s an inflammatory reaction, then might anti-inflammatory phytonutrients help? The bioflavonoids in citrus might help with the lactic acid buildup, but we may need to ramp up to the anthocyanin flavonoids in berries to deal with the inflammation.</p>\n<p>We know, for example, that if we eat about 45 cherries a day we can significantly <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/16549461\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">reduce</a> the levels of inflammatory markers like c-reactive protein in our bloodstream. Mushrooms (<strong><a title=\"Permanent link to Boosting Immunity While Reducing Inflammation\" href=\"https://nutritionfacts.org/video/boosting-immunity-while-reducing-inflammation/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Boosting Immunity While Reducing Inflammation</a></strong>), nuts (<strong><a title=\"Permanent link to Fighting Inflammation in a Nut Shell\" href=\"https://nutritionfacts.org/video/fighting-inflammation-in-a-nut-shell/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Fighting Inflammation in a Nut Shell</a></strong>), and purple potatoes (<strong><a title=\"Permanent link to Anti-Inflammatory Effects of Purple Potatoes\" href=\"https://nutritionfacts.org/video/anti-inflammatory-effects-of-purple-potatoes/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Anti-Inflammatory Effects of Purple Potatoes</a></strong>) may also reduce inflammation (along with plant foods in general, see <a title=\"Permanent link to Anti-Inflammatory Antioxidants\" href=\"https://nutritionfacts.org/video/anti-inflammatory-antioxidants/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\"><strong>Anti-Inflammatory Antioxidants</strong></a>) so much so that plant-based diets can be used to treat inflammatory conditions. See, for example, <strong><a title=\"Permanent link to Dietary Treatment of Crohn’s Disease\" href=\"https://nutritionfacts.org/video/achieving-remission-of-crohns-disease/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Dietary Treatment of Crohn’s Disease</a></strong>, and <strong><a title=\"Permanent link to Potassium and Autoimmune Disease\" href=\"https://nutritionfacts.org/video/potassium-and-autoimmune-disease/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Potassium and Autoimmune Disease</a></strong>. Animal products on the other hand, may increase inflammation through a variety of mechanisms, including endotoxins (<strong><a title=\"Permanent link to How Does Meat Cause Inflammation?\" href=\"https://nutritionfacts.org/2012/09/20/why-meat-causes-inflammation/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">How Does Meat Cause Inflammation?</a></strong>), arachidonic acid (<strong><a title=\"Permanent link to Chicken, Eggs, and Inflammation\" href=\"https://nutritionfacts.org/video/chicken-eggs-and-inflammation/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Chicken, Eggs, and Inflammation</a></strong>), and Neu5Gc (<strong><a title=\"Permanent link to The Inflammatory Meat Molecule Neu5Gc\" href=\"https://nutritionfacts.org/video/the-inflammatory-meat-molecule-neu5gc/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">The Inflammatory Meat Molecule Neu5Gc</a></strong>).</p>\n<p>But what about reducing muscle soreness?</p>\n<p>Researchers <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/16790484\" target=\"_blank\" rel=\"noopener\">took</a> some guys and made them flex their biceps against way too much weight over and over and over again, the next day the strength in their arms is way down—about a 30% drop—and they suffered serous soreness (See <a href=\"https://nutritionfacts.org/video/reducing-muscle-soreness-with-berries/\" target=\"_blank\" rel=\"noopener\"><strong>Reducing Muscle Soreness with Berries</strong></a>). But if they were drinking some cherry juice, their arms ended up hurting less and they were able to better preserve their strength. Why not just feed them cherries? Because we can’t do a placebo group since we can’t really create a convincing fake cherry, but we can make fake cherry juice in the form of cherry Kool-Aid.</p>\n<p>This was “the first <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/16790484\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">study</a> to examine the effect of the consumption of any cherry product on the symptoms of exercise induced muscle damage,” and it seemed to work. Follow-up <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/16790484\" target=\"_blank\" rel=\"noopener\">studies</a> show it also works on <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/19883392\" target=\"_blank\" rel=\"noopener\">reducing</a> muscle pain in long-distance runners, speeding recovery after a marathon, considered “the holy grail of exercise science.”</p>\n<p>A similar <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22111516\" target=\"_blank\" rel=\"noopener\">study</a> showing anti-inflammatory effects of eating blueberries took it a step further and actually paid athletes to take a muscle biopsy so they could see what’s happening to their muscles on a microscopic level. It’s like another <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/22301554\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">study</a> which showed how massage could decrease inflammation. At first I was like: “ooh, I wouldn’t mind being part of that study—free relaxing massage!” until I read the protocol: subjects got to rest a few minutes, then the scalpels come out and cut out some muscle samples. No thanks.</p>\n<p>And of course there are drugs—there are always drugs—but with drugs there are side effects. So the cherry study, as noted in an editorial comment, “may provide more of a sensible and realistic treatment option for those suffering from sore and damaged muscles. The scientific question of how to treat the damaged muscle is an important one, and these researchers should be applauded for finding a potential treatment that is not only practical, but one that can be enjoyed.”</p>\n<p>How about improving athletic performance more directly? See my video series on performance-enhancing vegetables described in my blog <strong><a title=\"Permanent link to Using Greens to Improve Athletic Performance\" href=\"https://nutritionfacts.org/2012/03/22/using-greens-to-improve-athletic-performance/\" target=\"_blank\" rel=\"noopener\" data-ls-seen=\"1\">Using Greens to Improve Athletic Performance</a></strong>.</p>\n<p><strong>-Michael Greger, M.D.</strong></p>\n<p>PS: If you haven’t yet, you can subscribe to my videos for free by <a href=\"https://nutritionfacts.us5.list-manage.com/subscribe?u=c1bae6687e1e6ab175fb56913&amp;id=40f9e497d1\" target=\"_blank\" rel=\"noopener\"><strong>clicking here</strong></a> and watch my full 2012 – 2015 presentations <strong><a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\" target=\"_blank\" rel=\"noopener\">Uprooting the Leading Causes of Death</a></strong>, <strong><a href=\"https://nutritionfacts.org/video/more-than-an-apple-a-day-preventing-our-most-common-diseases/\">More than an Apple a Day</a></strong>, <strong><a href=\"https://nutritionfacts.org/video/from-table-to-able/\">From Table to Able</a></strong>, and <strong><a href=\"https://nutritionfacts.org/video/food-as-medicine/\">Food as Medicine</a></strong>.</p>"
  }
}
