=== MaximePinot/nutritionfactsorg-data/json/schemas/video.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/video.schema.json",
    "title": "Video",
    "description": "A Video article from nutritionfacts.org",
    "type": "object",
    "properties": {
        "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/video\\/"
        },
        "YouTubeVideo": {
            "type": "object",
            "properties": {
                "Url": {
                    "type": "string",
                    "minLength": 24,
                    "format": "uri",
                    "pattern": "^https:\\/\\/(www\\.)?youtube\\.com\\/"
                }
            },
            "required": [
                "Url"
            ],
            "additionalProperties": false
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
        "Author": {
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1,
                    "enum": [
                        "Michael Greger M.D. FACLM",
                        "Kristine Dennis PhD, MPH"
                    ]
                }
            ]
        },
        "Volume": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object",
                    "properties": {
                        "Title": {
                            "type": "string",
                            "minLength": 1
                        },
                        "Url": {
                            "type": "string",
                            "minLength": 35,
                            "format": "uri",
                            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/volumes\\/"
                        }
                    },
                    "required": [
                        "Title",
                        "Url"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "License": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string",
                    "enum": [
                        "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"
                    ]
                },
                "Url": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "https://creativecommons.org/licenses/by-nc/4.0/"
                    ]
                }
            },
            "required": [
                "Name",
                "Url"
            ],
            "additionalProperties": false
        },
        "Description": {
            "type": "string",
            "minLength": 1
        },
        "Transcript": {
            "type": "string",
            "minLength": 1
        },
        "Sources": {
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "Title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "Url": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string",
                                "minLength": 1,
                                "format": "uri"
                            }
                        ]
                    }
                },
                "required": [
                    "Title",
                    "Url"
                ],
                "additionalProperties": false
            }
        },
        "Acknowledgements": {
            "type": "string",
            "minLength": 0
        },
        "Topics": {
            "type": "array",
            "items": {
                "type": "object",
                "minItems": 0,
                "uniqueItems": true,
                "properties": {
                    "Title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "Url": {
                        "type": "string",
                        "minLength": 35,
                        "format": "uri",
                        "pattern": "^https:\\/\\/nutritionfacts\\.org\\/topics\\/[\\w-]+\\/$"
                    }
                },
                "required": [
                    "Title",
                    "Url"
                ],
                "additionalProperties": false
            }
        },
        "DoctorsNote": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "Title",
        "Url",
        "YouTubeVideo",
        "UpdatedAt",
        "Author",
        "Volume",
        "License",
        "Description",
        "Transcript",
        "Sources",
        "Acknowledgements",
        "Topics",
        "DoctorsNote"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/cattlemens-association-has-beef-with-epic-study.json
{
  "Title": "Cattlemen’s Association Has Beef with Study",
  "Url": "https://nutritionfacts.org/video/cattlemens-association-has-beef-with-epic-study/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/F7wQdOhU7ac"
  },
  "UpdatedAt": "2012-09-05T11:11:44+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 10",
    "Url": "https://nutritionfacts.org/volumes/volume-10/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "Meat consumption is not only associated with weight gain, but specifically abdominal obesity, which is the most metabolically concerning.",
  "Transcript": "The National Cattlemen’s Beef Association was not happy about the findings of the EPIC study, one of the largest studies on human nutrition ever performed—which, as we’ve seen recently, found that those who eat any kind of meat go on to gain significantly more weight than those who eat less—even eating the same number of calories.\nOne of the beef association’s speakers wrote to the American Journal of Clinical Nutrition, complaining that “Meat intake’s influence on body fatness cannot be assessed without measurement of body fat.” Maybe, the cattlemen argued, the pounds that the meateaters packed on was muscle mass, not fat. Maybe they were becoming beefier, not fatter.\nFine, the researcher answered. We’ll not just measure obesity, but abdominal obesity—the worst kind. So, they took a small sample out of the study, a sample of 91,214 people, and found the exact same thing. Even eating the same number of calories, the more meat we eat, the more our belly grows. And even calculated how much our waistline could be predicted to expand, based on our daily meat consumption. So, one can plan ahead for the new pants one might need to buy.\nThough nothing comes close to the EPIC study in scale, other recent studies have found the same thing. In Spain, nut and vegetable consumption was recently associated with having a slimmer waist, and meat and meat product consumption with a wider one. Another new study, this one out of Belgium, concluded that animal protein intake was associated with bigger body mass index and waistline, whereas plant protein intake was associated with a smaller BMI and slimmer waist—indicating that the intakes of plant protein could offer a potential protective effect against overweight and obesity.\nTo see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring watch the above video. This is just an approximation of the audio contributed by Kerry Skinner.\nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Astrup A, Clifton P, Layman DK, Mattes RD, Westerterp-Plantenga MS. Meat intake's influence on body fatness cannot be assessed without measurement of body fat. Am J Clin Nutr. 2010 Nov;92(5):1274-5; author reply 1275-6.",
      "Url": "http://www.ajcn.org/content/92/5/1274.full.pdf+html"
    },
    {
      "Title": "Casas-Agustench P, Bulló M, Ros E, Basora J, Salas-Salvadó J; Nureta-PREDIMED investigators. Cross-sectional association of nut intake with adiposity in a Mediterranean population. Nutr Metab Cardiovasc Dis. 2011 Jul;21(7):518-25.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/20219336"
    },
    {
      "Title": "Lin Y, Bolca S, Vandevijvere S, De Vriese S, Mouratidou T, De Neve M, Polet A, Van Oyen H, Van Camp J, De Backer G, De Henauw S, Huybrechts I. Plant and animal protein intake and its association with overweight and obesity among the Belgian population. Br J Nutr. 2011 Apr;105(7):1106-16.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/21144092"
    },
    {
      "Title": "Vergnaud AC, Norat T, Romaguera D, Mouw T, May AM, Travier N, Luan J, Wareham N, Slimani N, Rinaldi S, Couto E, Clavel-Chapelon F, Boutron-Ruault MC, Cottet V, Palli D, Agnoli C, Panico S, Tumino R, Vineis P, Agudo A, Rodriguez L, Sanchez MJ, Amiano P, Barricarte A, Huerta JM, Key TJ, Spencer EA, Bueno-de-Mesquita B, Büchner FL, Orfanos P, Naska A, Trichopoulou A, Rohrmann S, Hermann S, Boeing H, Buijsse B, Johansson I, Hellstrom V, Manjer J, Wirfält E, Jakobsen MU, Overvad K, Tjonneland A, Halkjaer J, Lund E, Braaten T, Engeset D, Odysseos A, Riboli E, Peeters PH. Meat consumption and prospective weight change in participants of the EPIC-PANACEA study. Am J Clin Nutr. 2010 Aug;92(2):398-407.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/20592131"
    }
  ],
  "Acknowledgements": "",
  "Topics": [
    {
      "Title": "abdominal fat",
      "Url": "https://nutritionfacts.org/topics/abdominal-fat/"
    },
    {
      "Title": "animal fat",
      "Url": "https://nutritionfacts.org/topics/animal-fat/"
    },
    {
      "Title": "animal products",
      "Url": "https://nutritionfacts.org/topics/animal-products/"
    },
    {
      "Title": "animal protein",
      "Url": "https://nutritionfacts.org/topics/animal-protein/"
    },
    {
      "Title": "body fat",
      "Url": "https://nutritionfacts.org/topics/body-fat/"
    },
    {
      "Title": "calories",
      "Url": "https://nutritionfacts.org/topics/calories/"
    },
    {
      "Title": "EPIC Study",
      "Url": "https://nutritionfacts.org/topics/epic-study/"
    },
    {
      "Title": "fat",
      "Url": "https://nutritionfacts.org/topics/fat/"
    },
    {
      "Title": "industry influence",
      "Url": "https://nutritionfacts.org/topics/industry-influence/"
    },
    {
      "Title": "meat",
      "Url": "https://nutritionfacts.org/topics/meat/"
    },
    {
      "Title": "nuts",
      "Url": "https://nutritionfacts.org/topics/nuts/"
    },
    {
      "Title": "obesity",
      "Url": "https://nutritionfacts.org/topics/obesity/"
    },
    {
      "Title": "plant protein",
      "Url": "https://nutritionfacts.org/topics/plant-protein/"
    },
    {
      "Title": "protein",
      "Url": "https://nutritionfacts.org/topics/protein/"
    },
    {
      "Title": "vegetables",
      "Url": "https://nutritionfacts.org/topics/vegetables/"
    },
    {
      "Title": "weight loss",
      "Url": "https://nutritionfacts.org/topics/weight-loss/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>The findings of the EPIC study linking meat consumption to weight gain can be found in <a href=\"https://nutritionfacts.org/video/meat-and-weight-gain-in-the-panacea-study/\" rel=\"nofollow\">Meat and Weight Gain in the PANACEA Study</a>. The Cattlemen were also vocal in questioning the federal dietary guidelines; see <a href=\"https://nutritionfacts.org/video/dietary-guidelines-corporate-guidance/\" rel=\"nofollow\">Dietary Guidelines: Corporate Guidance</a>. Tomorrow, we’ll cover the various ways excess body fat can be measured.</p>\n<p>For more context, check out my associated blog posts <a href=\"https://nutritionfacts.org/blog/poultry-paunch-meat-weight-gain/\">Poultry Paunch: Meat &amp; Weight Gain</a>; <a href=\"https://nutritionfacts.org/2013/10/24/can-cellulite-be-treated-with-diet/\">Diet and Cellulite</a>; and <a href=\"https://nutritionfacts.org/2013/07/30/is-coconut-oil-good-for-you/\">Is Coconut Oil Bad For You?</a></p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/nonhuman-molecules-lining-our-arteries.json
{
  "Title": "Nonhuman Molecules Lining our Arteries",
  "Url": "https://nutritionfacts.org/video/nonhuman-molecules-lining-our-arteries/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/hy5BPWnaFik"
  },
  "UpdatedAt": "2012-12-17T12:40:38+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 11",
    "Url": "https://nutritionfacts.org/volumes/volume-11/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "The foreign meat molecule Neu5Gc builds up in human tumors and atherosclerotic plaques, and may play an inflammatory role in the progression of both diseases.",
  "Transcript": "Below is an approximation of this video’s audio content. To see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring, watch the above video.\nThe foreign meat molecule Neu5Gc tends to accumulate, particularly in the lining of hollow organs—where carcinomas, like breast cancer, develop inside your glands, and in the lining blood of vessels, where atherosclerosis occurs.\n“Evidence for a novel human-specific xeno-auto-antibody response against vascular endothelium.”\n“The Neu5Gc accumulation may facilitate production of anti-Neu5Gc antibodies and further aggravate chronic inflammation in atherosclerosis progression”—in addition to just cancer.\nHere, you can see it, stained in red, lining the aorta of a human autopsy sample. And here, you can actually see it inside atherosclerotic plaques, providing multiple pathways for accelerating inflammation in this disease.\nRemember, we lost the ability to make this substance millions of years ago. Whether it’s feeding inflammation to our cancer, or to our heart disease, it all came from the animal products in our diet.\n“Taken together, these findings suggest a mechanism whereby anti-Neu5Gc antibodies can initiate, perpetuate, and/or exacerbate an inflammatory response at the endothelium [the lining of our arteries], potentially playing a role in disease states such as atherosclerosis, [where] vascular inflammation is involved. Neu5Gc is a novel dietary and human- specific ‘xeno-auto-antigen’ that may exacerbate a variety of vascular pathologies.”\nThey go onto note that if we actually ate what the USDA recommends for protein, in the form of meat and dairy, we could ingest as much 10 milligrams of Neu5Gc per day, which is 10 milligrams more than we evolved to have in our bodies since, as a species, we stopped making it millions of years ago, before we started eating meat.\n“…[N]ovel therapeutic approaches to reducing or dampening flares of immunologic responses against the endothelium…could include reduction of dietary Neu5Gc intake and accumulation through simple diet-based interventions.”\nNot so novel, perhaps, but definitely simple. This inflammatory cancer promoter “has never been reported in plants.”\nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Hedlund M, Padler-Karavani V, Varki NM, Varki A. Evidence for a human-specific mechanism for diet and antibody-mediated inflammation in carcinoma progression. Proc Natl Acad Sci U S A. 2008 Dec 2;105(48):18936-41.",
      "Url": "http://www.pnas.org/content/105/48/18936.full.pdf+html"
    },
    {
      "Title": "Pham T, Gregg CJ, Karp F, Chow R, Padler-Karavani V, Cao H, Chen X, Witztum JL, Varki NM, Varki A. Evidence for a novel human-specific xeno-auto-antibody response against vascular endothelium. Blood. 2009 Dec 10;114(25):5225-35.",
      "Url": "http://bloodjournal.hematologylibrary.org/content/114/25/5225.full.pdf+html"
    },
    {
      "Title": "Varki A. Colloquium paper: uniquely human evolution of sialic acid genetics and biology. Proc Natl Acad Sci U S A. 2010 May 11;107 Suppl 2:8939-46.",
      "Url": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3024026/pdf/pnas.200914634.pdf"
    }
  ],
  "Acknowledgements": "",
  "Topics": [
    {
      "Title": "animal products",
      "Url": "https://nutritionfacts.org/topics/animal-products/"
    },
    {
      "Title": "animal protein",
      "Url": "https://nutritionfacts.org/topics/animal-protein/"
    },
    {
      "Title": "breast cancer",
      "Url": "https://nutritionfacts.org/topics/breast-cancer/"
    },
    {
      "Title": "cancer",
      "Url": "https://nutritionfacts.org/topics/cancer/"
    },
    {
      "Title": "cardiovascular disease",
      "Url": "https://nutritionfacts.org/topics/cardiovascular-disease/"
    },
    {
      "Title": "dairy",
      "Url": "https://nutritionfacts.org/topics/dairy/"
    },
    {
      "Title": "heart disease",
      "Url": "https://nutritionfacts.org/topics/heart-disease/"
    },
    {
      "Title": "inflammation",
      "Url": "https://nutritionfacts.org/topics/inflammation/"
    },
    {
      "Title": "meat",
      "Url": "https://nutritionfacts.org/topics/meat/"
    },
    {
      "Title": "Neu5Gc",
      "Url": "https://nutritionfacts.org/topics/neu5gc/"
    },
    {
      "Title": "plant protein",
      "Url": "https://nutritionfacts.org/topics/plant-protein/"
    },
    {
      "Title": "Plant-Based Diets",
      "Url": "https://nutritionfacts.org/topics/plant-based-diets/"
    },
    {
      "Title": "protein",
      "Url": "https://nutritionfacts.org/topics/protein/"
    },
    {
      "Title": "USDA",
      "Url": "https://nutritionfacts.org/topics/usda/"
    },
    {
      "Title": "vegans",
      "Url": "https://nutritionfacts.org/topics/vegans/"
    },
    {
      "Title": "vegetable protein",
      "Url": "https://nutritionfacts.org/topics/vegetable-protein/"
    },
    {
      "Title": "vegetarians",
      "Url": "https://nutritionfacts.org/topics/vegetarians/"
    },
    {
      "Title": "women's health",
      "Url": "https://nutritionfacts.org/topics/womens-health/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>See <a href=\"https://nutritionfacts.org/video/the-inflammatory-meat-molecule-neu5gc/\">The Inflammatory Meat Molecule Neu5Gc</a> for background, and <a href=\"https://nutritionfacts.org/video/how-tumors-use-meat-to-grow-xeno-autoantibodies/\">How Tumors Use Meat to Grow: Xeno-Autoantibodies</a> for the role it might play in cancer growth. Inflammation is also caused by exogenous endotoxins (see <a href=\"https://nutritionfacts.org/video/the-exogenous-endotoxin-theory/\">The Exogenous Endotoxin Theory</a>), and is one of the three steps en route to fatal heart disease; see <a href=\"https://nutritionfacts.org/video/arterial-acne/\">Arterial Acne</a>; <a href=\"https://nutritionfacts.org/video/blocking-the-first-step-of-heart-disease/\">Blocking the First Step of Heart Disease</a>; and <a href=\"https://nutritionfacts.org/video/making-our-arteries-less-sticky/\">Making Our Arteries Less Sticky</a>. Antioxidants found predominantly in plants (see <a href=\"https://nutritionfacts.org/video/antioxidant-power-of-plant-foods-versus-animal-foods/\">Antioxidant Power of Plant Foods Versus Animal Foods</a>) may also decrease inflammation within the body (see <a href=\"https://nutritionfacts.org/video/anti-inflammatory-antioxidants/\">Anti-Inflammatory Antioxidants</a>). Nuts may be particularly useful in this regard; see <a href=\"https://nutritionfacts.org/video/fighting-inflammation-in-a-nut-shell/\">Fighting Inflammation in a Nut Shell.</a> Tomorrow, we’ll close out the Neu5Gc story with <a href=\"https://nutritionfacts.org/video/meat-may-exceed-daily-allowance-of-irony/\">Meat May Exceed Daily Allowance of Irony</a>.</p>\n<p>For further context, check out my associated blog post: <a href=\"https://nutritionfacts.org/2013/05/16/plant-based-diets-for-rheumatoid-arthritis/\">Plant-Based Diets for Rheumatoid Arthritis</a>.</p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/skim-milk-and-acne.json
{
  "Title": "Skim Milk and Acne",
  "Url": "https://nutritionfacts.org/video/skim-milk-and-acne/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/guniBUojHAM"
  },
  "UpdatedAt": "2012-05-11T12:00:21+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 8",
    "Url": "https://nutritionfacts.org/volumes/volume-8/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "Three Harvard studies linking acne with dairy consumption in adolescent girls and boys blamed the sex steroid hormone content naturally found in cow’s milk (even without added hormones)—particularly skim.",
  "Transcript": "The Harvard Nurses’ Study, published in the prestigious Journal of the American Academy of Dermatology, funded in part by none other than the National Dairy Council itself, found that the association between milk intake during adolescence and severe physician-diagnosed teenage acne was even more marked for skim milk than for other forms of milk.\nThis may be because there is so much more estrogen in skim milk. Researchers found 15 steroid sex hormones in commercial milk right off the shelves, and the highest levels were found in skim milk, compared to 2% and whole.\nThis study involved asking women what they ate years ago in high school, though. Who can even remember?\nSo, the next year, Harvard researchers studied milk consumption and acne in adolescent girls directly, following 6,000 girls, aged 9-15, for a few years, and found the same thing: a positive link between intake of milk and acne. Maybe it’s just girls, though?\nSo, next, they studied milk consumption and acne in teenage boys, and here we go again: a positive association between intake of skim milk and acne.\nAnd it doesn’t appear to be an issue with bovine growth hormone injections, or added steroids. This is just what milk contains naturally. It should surprise no one that milk contains such a heavy complement of growth-enhancing hormones. Milk is, after all, specifically designed to make things grow.\nTo see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring, watch the above video. This is just an approximation of the audio contributed by veganmontreal. \nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Adebamowo CA, Spiegelman D, Berkey CS, Danby FW, Rockett HH, Colditz GA, Willett WC, Holmes MD. Milk consumption and acne in adolescent girls. Dermatol Online J. 2006 May 30;12(4):1.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/17083856"
    },
    {
      "Title": "Adebamowo CA, Spiegelman D, Danby FW, Frazier AL, Willett WC, Holmes MD. High school dietary dairy intake and teenage acne. J Am Acad Dermatol. 2005 Feb;52(2):207-14.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/15692464"
    },
    {
      "Title": "Danby FW. Acne and milk, the diet myth, and beyond. J Am Acad Dermatol. 2005 Feb;52(2):360-2.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/15692488"
    }
  ],
  "Acknowledgements": "",
  "Topics": [
    {
      "Title": "acne",
      "Url": "https://nutritionfacts.org/topics/acne/"
    },
    {
      "Title": "adolescence",
      "Url": "https://nutritionfacts.org/topics/adolescence/"
    },
    {
      "Title": "dairy",
      "Url": "https://nutritionfacts.org/topics/dairy/"
    },
    {
      "Title": "estrogen",
      "Url": "https://nutritionfacts.org/topics/estrogen/"
    },
    {
      "Title": "Harvard",
      "Url": "https://nutritionfacts.org/topics/harvard/"
    },
    {
      "Title": "Harvard Nurses' Health Study",
      "Url": "https://nutritionfacts.org/topics/harvard-nurses-health-study/"
    },
    {
      "Title": "hormones",
      "Url": "https://nutritionfacts.org/topics/hormones/"
    },
    {
      "Title": "milk",
      "Url": "https://nutritionfacts.org/topics/milk/"
    },
    {
      "Title": "skim milk",
      "Url": "https://nutritionfacts.org/topics/skim-milk/"
    },
    {
      "Title": "skin health",
      "Url": "https://nutritionfacts.org/topics/skin-health/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>Be sure to see <a href=\"https://nutritionfacts.org/video/national-dairy-council-on-acne-and-milk/\" rel=\"nofollow\">National Dairy Council on Acne and Milk</a> and <a href=\"https://nutritionfacts.org/video/the-acne-promoting-effects-of-milk/\">The Acne-Promoting Effects of Milk</a> in this three-part video series on the latest science on milk as a risk factor for acne development.</p>\n<p>For further context, check out my associated blog posts: <a href=\"https://nutritionfacts.org/blog/skim-milk-and-acne/\">Skim Milk and Acne</a>; <a href=\"https://nutritionfacts.org/2012/05/03/stool-size-and-breast-cancer-risk/\" rel=\"nofollow\">Stool Size and Breast Cancer Risk</a>; and <a href=\"https://nutritionfacts.org/2013/10/10/flaxseeds-for-sensitive-skin/\">Treating Sensitive Skin From the Inside Out</a>.</p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}
