=== MaximePinot/nutritionfactsorg-data/json/schemas/video.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/video.schema.json",
    "title": "Video",
    "description": "A Video article from nutritionfacts.org",
    "type": "object",
    "properties": {
        "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/video\\/"
        },
        "YouTubeVideo": {
            "type": "object",
            "properties": {
                "Url": {
                    "type": "string",
                    "minLength": 24,
                    "format": "uri",
                    "pattern": "^https:\\/\\/(www\\.)?youtube\\.com\\/"
                }
            },
            "required": [
                "Url"
            ],
            "additionalProperties": false
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
        "Author": {
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1,
                    "enum": [
                        "Michael Greger M.D. FACLM",
                        "Kristine Dennis PhD, MPH"
                    ]
                }
            ]
        },
        "Volume": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object",
                    "properties": {
                        "Title": {
                            "type": "string",
                            "minLength": 1
                        },
                        "Url": {
                            "type": "string",
                            "minLength": 35,
                            "format": "uri",
                            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/volumes\\/"
                        }
                    },
                    "required": [
                        "Title",
                        "Url"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "License": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string",
                    "enum": [
                        "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"
                    ]
                },
                "Url": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "https://creativecommons.org/licenses/by-nc/4.0/"
                    ]
                }
            },
            "required": [
                "Name",
                "Url"
            ],
            "additionalProperties": false
        },
        "Description": {
            "type": "string",
            "minLength": 1
        },
        "Transcript": {
            "type": "string",
            "minLength": 1
        },
        "Sources": {
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "Title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "Url": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string",
                                "minLength": 1,
                                "format": "uri"
                            }
                        ]
                    }
                },
                "required": [
                    "Title",
                    "Url"
                ],
                "additionalProperties": false
            }
        },
        "Acknowledgements": {
            "type": "string",
            "minLength": 0
        },
        "Topics": {
            "type": "array",
            "items": {
                "type": "object",
                "minItems": 0,
                "uniqueItems": true,
                "properties": {
                    "Title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "Url": {
                        "type": "string",
                        "minLength": 35,
                        "format": "uri",
                        "pattern": "^https:\\/\\/nutritionfacts\\.org\\/topics\\/[\\w-]+\\/$"
                    }
                },
                "required": [
                    "Title",
                    "Url"
                ],
                "additionalProperties": false
            }
        },
        "DoctorsNote": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "Title",
        "Url",
        "YouTubeVideo",
        "UpdatedAt",
        "Author",
        "Volume",
        "License",
        "Description",
        "Transcript",
        "Sources",
        "Acknowledgements",
        "Topics",
        "DoctorsNote"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/why-dont-health-insurers-encourage-healthier-eating.json
{
  "Title": "Why Don’t Health Insurers Encourage Healthier Eating?",
  "Url": "https://nutritionfacts.org/video/why-dont-health-insurers-encourage-healthier-eating/",
  "YouTubeVideo": {
    "Url": "https://youtube.com/v/HsOdTyIT0GY"
  },
  "UpdatedAt": "2022-08-03T11:50:29+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 58",
    "Url": "https://nutritionfacts.org/volumes/volume-58/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "Why don’t more big payors in health care embrace plant-based eating?",
  "Transcript": "Below is an approximation of this video’s audio content. To see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring, watch the above video.\nMany of the diseases that cause a constant drain on health care budgets can be prevented by proper nutrition; so, why aren’t the big payors getting involved? I mean even like a 1 percent decline in excess body fat could alone save tens of billions. You’d think at least the health insurance industry would try to get people to eat healthier to try to pay out less money. Well, one could say the insurance industry actually benefits from high healthcare costs because these rising costs are simply passed on to both individuals and employers in terms of higher premiums, and insurers take a fixed percentage of these premiums as increasing profits. They get a piece of the pie; so, the bigger the pie—the unhealthier everyone is—the bigger their piece. As such, insurers have not done as much as they could to help reduce health care costs because lower costs would hurt their bottom line.\n“What if there was a medication that could successfully treat and even reverse heart disease, type 2 diabetes, high blood pressure, and many other chronic conditions without any negative side effects and offered the promise of dramatically reduced health care costs?” Imagine all the advertising there would be to promote it; imagine how much they would charge. A drug that could not just treat but cure diabetes and these other diseases? “Then, what if you were told this medication exists today, is available to everyone in unlimited quantities at a low cost, but the vast majority of the American public has never heard about it.” Do you want a solution to significantly reduce health care costs? The solution is to use food as medical treatment, specifically, foods made from minimally processed plants.\n“One of the main barriers is simply the current widespread belief that once someone has a chronic condition, such as heart disease or type 2 diabetes, there is very little that can be done to actually reverse the disease, and the best outcome possible is to maintain the condition so that it just doesn’t get any worse. The fact that a whole food plant-based approach provides a safe, effective, low-cost alternative to not just eliminating symptoms but potentially reversing the underlying condition without drugs or surgery is unknown to a vast majority of Americans. In contrast to the pharmaceutical industry that spends large sums to market new drugs,…there are not big profits in promoting a plant-based diet.”\nThe politics surrounding healthcare is who’s-going-to-pay-for-it, instead of what kind of healthcare is best, and the evidence is overwhelming that a whole food, plant-based diet provides the best opportunity to not only reduce the growth in spending, but actually decrease total health care costs more than any drug, medical procedure, insurance reform, or provider payment model out there.\nThankfully, the word is spreading. A review of the evidence published in Kaiser Permanente’s journal concluded that “[p]hysicians should consider recommending a plant-based diet to all their patients, especially those with high blood pressure, diabetes, cardiovascular disease, or obesity. Kaiser has followed up with user friendly guides (freely available online) for both physicians and patients, explaining the benefits and practical aspects of implementing a plant-based diet.” So hey, why aren’t all insurers sending out such information to all their members? You know how all the drug ads are, like, “Ask your doctor if this drug is right for you.” Well, members could be prompted to ask their physicians about the ability of a plant-based diet to reduce or eliminate prescription drug use and reverse disease. Though of course, these materials would also have to list all the side effects. Side effects include: “increased energy, lower blood pressure, improved digestion, all while eating unlimited quantities of satisfying food.” Ask your doctor if plants are right for you.\nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Beckman K. Challenge to the Insurance Industry: A Solution to Significantly Reduce Health Care Costs. Cut Health Care Costs. July 2016.",
      "Url": "http://www.cuthealthcarecosts.org/ChallengetotheInsuranceIndustry.pdf"
    },
    {
      "Title": "Kaiser Permanente. SCPMG Regional Health Education 15116 (3/2019).",
      "Url": "https://1w7lsd145y0x22fgi71wekk2-wpengine.netdna-ssl.com/wp-content/uploads/15116-plant-based-eating.pdf"
    },
    {
      "Title": "Kaiser Permanente. SCPMG Regional Health Education MH1537 (8/2013).",
      "Url": "https://thrive.kaiserpermanente.org/care-near-you/northern-california/santarosa/wp-content/uploads/sites/15/2015/09/New-Plant-Based-Booklet-1214_tcm28-781815.pdf"
    },
    {
      "Title": "Szucs TD, Stoffel AW. Nutrition and health—Why payors should get involved. Nutrition. 2016;32(5):615-6.",
      "Url": "https://pubmed.ncbi.nlm.nih.gov/26796149/"
    }
  ],
  "Acknowledgements": "Motion graphics by Avo Media",
  "Topics": [
    {
      "Title": "blood pressure",
      "Url": "https://nutritionfacts.org/topics/blood-pressure/"
    },
    {
      "Title": "cardiovascular disease",
      "Url": "https://nutritionfacts.org/topics/cardiovascular-disease/"
    },
    {
      "Title": "chronic diseases",
      "Url": "https://nutritionfacts.org/topics/chronic-diseases/"
    },
    {
      "Title": "diabetes",
      "Url": "https://nutritionfacts.org/topics/diabetes/"
    },
    {
      "Title": "heart disease",
      "Url": "https://nutritionfacts.org/topics/heart-disease/"
    },
    {
      "Title": "heart health",
      "Url": "https://nutritionfacts.org/topics/heart-health/"
    },
    {
      "Title": "high blood pressure",
      "Url": "https://nutritionfacts.org/topics/high-blood-pressure/"
    },
    {
      "Title": "hypertension",
      "Url": "https://nutritionfacts.org/topics/hypertension/"
    },
    {
      "Title": "industry influence",
      "Url": "https://nutritionfacts.org/topics/industry-influence/"
    },
    {
      "Title": "medical profession",
      "Url": "https://nutritionfacts.org/topics/medical-profession/"
    },
    {
      "Title": "Plant-Based Diets",
      "Url": "https://nutritionfacts.org/topics/plant-based-diets/"
    },
    {
      "Title": "vegans",
      "Url": "https://nutritionfacts.org/topics/vegans/"
    },
    {
      "Title": "vegetarians",
      "Url": "https://nutritionfacts.org/topics/vegetarians/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>For more on treating the underlying cause of lifestyle diseases, see:</p>\n<ul>\n<li><a href=\"https://nutritionfacts.org/video/lifestyle-medicine-treating-the-causes-of-disease/\">Lifestyle Medicine: Treating the Causes of Disease</a></li>\n<li><a href=\"https://nutritionfacts.org/video/convincing-doctors-to-embrace-lifestyle-medicine/\">Convincing Doctors to Embrace Lifestyle Medicine</a></li>\n<li><a href=\"https://nutritionfacts.org/video/what-diet-should-physicians-recommend/\">What Diet Should Physicians Recommend?</a></li>\n<li><a href=\"https://nutritionfacts.org/video/the-actual-benefit-of-diet-vs-drugs/\">The Actual Benefit of Diet vs. Drugs</a></li>\n</ul>\n<p>For health in the workplace, check out <a href=\"https://nutritionfacts.org/video/a-workplace-wellness-program-that-works/\">A Workplace Wellness Program That Works</a></p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/airborne-mrsa.json
{
  "Title": "Airborne MRSA",
  "Url": "https://nutritionfacts.org/video/airborne-mrsa/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/SP7OJHpX-V4"
  },
  "UpdatedAt": "2011-11-22T13:00:47+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 6",
    "Url": "https://nutritionfacts.org/volumes/6/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "Methicillin-resistant Staphylococcus aureus “superbug” found not only contaminating the U.S. retail meat supply, but isolated from air samples outside swine CAFOs.",
  "Transcript": "“From Pigs to People. The Emergence of a New Superbug. The discovery of a novel strain of MRSA able to jump from livestock to humans.”\nIn this study, showing widespread and pervasive staph bacteria contamination of the U.S. meat supply this year—or at least in turkey, pork, chicken, and beef.\nThis is the scariest column. Oxacillin, which is in the same class as methicillin. These were of MRSA, methicillin-resistant Staph aureus, now killing more Americans than AIDS every year in the United States—and now found in our retail meat supply.\nFrom an overview of the problem, published last year out of the University of Iowa, overall MRSA prevalence in U.S. swine was found to be 11%, and higher in confinement operations—for example, where pregnant pigs are kept in crates for months on end.\nAnd indeed, testing the workers, those working in confinement operations had a higher prevalence of MRSA in their nostrils. But they weren’t necessarily picking their nose. Airborne MRSA was found floating around, even outside the confinement buildings. Because of this, concern has arisen about MRSA as a potential environmental and public health hazard.\nTo see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring, watch the above video. This is just an approximation of the audio contributed by Peter Mellor. \nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Ferber D. Infectious disease. From pigs to people: the emergence of a new superbug. Science. 2010 Aug 27;329(5995):1010-1.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/20798295"
    },
    {
      "Title": "Harper AL, Ferguson DD, Leedom Larson KR, Hanson BM, Male MJ, Donham KJ, Smith TC. An overview of livestock-associated MRSA in agriculture. J Agromedicine. 2010 Apr;15(2):101-4.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/20407991"
    },
    {
      "Title": "Waters AE, Contente-Cuomo T, Buchhagen J, Liu CM, Watson L, Pearce K, Foster JT, Bowers J, Driebe EM, Engelthaler DM, Keim PS, Price LB. Multidrug-Resistant Staphylococcus aureus in US Meat and Poultry. Clin Infect Dis. 2011 May;52(10):1227-30.",
      "Url": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3079400/pdf/cir181.pdf"
    }
  ],
  "Acknowledgements": "",
  "Topics": [
    {
      "Title": "AIDS",
      "Url": "https://nutritionfacts.org/topics/aids/"
    },
    {
      "Title": "antibiotics",
      "Url": "https://nutritionfacts.org/topics/antibiotics/"
    },
    {
      "Title": "beef",
      "Url": "https://nutritionfacts.org/topics/beef/"
    },
    {
      "Title": "chicken",
      "Url": "https://nutritionfacts.org/topics/chicken/"
    },
    {
      "Title": "factory farming practices",
      "Url": "https://nutritionfacts.org/topics/factory-farming-practices/"
    },
    {
      "Title": "food poisoning",
      "Url": "https://nutritionfacts.org/topics/food-poisoning/"
    },
    {
      "Title": "foodborne illness",
      "Url": "https://nutritionfacts.org/topics/foodborne-illness/"
    },
    {
      "Title": "meat",
      "Url": "https://nutritionfacts.org/topics/meat/"
    },
    {
      "Title": "MRSA",
      "Url": "https://nutritionfacts.org/topics/mrsa/"
    },
    {
      "Title": "pork",
      "Url": "https://nutritionfacts.org/topics/pork/"
    },
    {
      "Title": "poultry",
      "Url": "https://nutritionfacts.org/topics/poultry/"
    },
    {
      "Title": "staph infection",
      "Url": "https://nutritionfacts.org/topics/staph-infection/"
    },
    {
      "Title": "turkey",
      "Url": "https://nutritionfacts.org/topics/turkey/"
    },
    {
      "Title": "zoonotic disease",
      "Url": "https://nutritionfacts.org/topics/zoonotic-disease/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>Be sure to check out my <a href=\"https://nutritionfacts.org/topics/pork/\" rel=\"nofollow\">other videos on pork</a> and <a href=\"https://nutritionfacts.org/topics/foodborne-illness/\" rel=\"nofollow\">foodborne illness</a>.</p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/diet-or-exercise-whats-more-important-for-weight-loss.json
{
  "Title": "Diet vs. Exercise for Weight Loss",
  "Url": "https://nutritionfacts.org/video/diet-or-exercise-whats-more-important-for-weight-loss/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/LFa0t2X0hMk"
  },
  "UpdatedAt": "2012-09-03T10:59:14+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 10",
    "Url": "https://nutritionfacts.org/volumes/volume-10/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "When asked whether food and beverage consumption, or physical activity, was more important, the majority of people get the answer wrong.",
  "Transcript": "When trying to lose weight, which is most important: diet or exercise? This is what a survey found recently: “The vast majority of those trying to lose or maintain weight believe that both monitoring food and beverage consumption and physical activity are equally important in weight maintenance and weight loss.” Most people go with equally important, and then exercise, and then diet. And, most people are wrong.\nIdentified as one of the most common misconceptions about obesity in this recent review, the “Confusion about the leverage of exercise on body weight.” “Unfortunately, the energy balance equation [you know, calories in have to equal calories out] suggests that energy intake and energy expenditure occupy equivalent roles in determining energy balance, when in fact the factors governing energy intakes influence the energy balance far more powerfully than the factors determining resting energy expenditure.” \nWhat we put in our mouths is most important. For example, to walk off the calories found in single pat of butter, you’d have to add an extra 700 yards to your stroll that evening. A quarter-mile jog for each sardine we put in our mouth—and that’s just the edible part. And those who choose to eat two chicken legs better get out on their own two legs, and run an extra three miles that day to outrun weight gain. And that’s for steamed chicken; skin removed.\nTo see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring watch the above video. This is just an approximation of the audio contributed by Kerry Skinner.\nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Ding EL, Hu FB. Commentary: Relative importance of diet vs physical activity for health. Int J Epidemiol. 2010 Feb;39(1):209-11; author reply 213-4.",
      "Url": "http://ije.oxfordjournals.org/content/39/1/209.full.pdf+html"
    },
    {
      "Title": "Flatt JP. Issues and misconceptions about obesity. Obesity (Silver Spring). 2011 Apr;19(4):676-86.",
      "Url": "http://onlinelibrary.wiley.com/doi/10.1038/oby.2011.7/abstract"
    },
    {
      "Title": "International Food Information Council Foundation. 2011. Food & Health Survey: Consumer Attitudes Toward Food Safety, Nutrition & Health.",
      "Url": "http://www.foodinsight.org/Content/3840/2011%20IFIC%20FDTN%20Food%20and%20Health%20Survey.pdf"
    }
  ],
  "Acknowledgements": "Images thanks to Evan-Amos via Wikimedia Commons; Mike Baird via flickr; NOAA; and Luan",
  "Topics": [
    {
      "Title": "body fat",
      "Url": "https://nutritionfacts.org/topics/body-fat/"
    },
    {
      "Title": "butter",
      "Url": "https://nutritionfacts.org/topics/butter/"
    },
    {
      "Title": "calories",
      "Url": "https://nutritionfacts.org/topics/calories/"
    },
    {
      "Title": "chicken",
      "Url": "https://nutritionfacts.org/topics/chicken/"
    },
    {
      "Title": "exercise",
      "Url": "https://nutritionfacts.org/topics/exercise/"
    },
    {
      "Title": "obesity",
      "Url": "https://nutritionfacts.org/topics/obesity/"
    },
    {
      "Title": "poultry",
      "Url": "https://nutritionfacts.org/topics/poultry/"
    },
    {
      "Title": "sardines",
      "Url": "https://nutritionfacts.org/topics/sardines/"
    },
    {
      "Title": "weight loss",
      "Url": "https://nutritionfacts.org/topics/weight-loss/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p class=\"p1\"><span class=\"s1\">This will look familiar to those who’ve seen my 2012 presentation (either live or vicariously at <a href=\"https://nutritionfacts.org/video/uprooting-the-leading-causes-of-death/\"><span class=\"s2\">Uprooting the Leading Causes of Death</span></a>). Tomorrow I cover the wild finding about meat’s affect on weight in <a href=\"https://nutritionfacts.org/video/meat-and-weight-gain-in-the-panacea-study/\"><span class=\"s2\">Meat and Weight Gain in the PANACEA Study</span></a>. Note the caloric expenditure equivalencies I present here are assuming no dietary compensation, something seen quite dramatically, for example, in nut consumption in <a href=\"https://nutritionfacts.org/video/testing-the-dietary-compensation-theory/\"><span class=\"s2\">Testing the Dietary Compensation Theory</span></a>. Given how hard it is to work off food, let’s make our calories count by choosing the most nutrient dense foods. <a href=\"https://nutritionfacts.org/video/calculate-your-healthy-eating-score/\"><span class=\"s2\">Calculate Your Healthy Eating Score</span></a> may be a good place to start.</span></p>\n<p class=\"p2\"><span class=\"s3\">For further context, check out my associated blog posts: <a href=\"https://nutritionfacts.org/blog/treadmill-desks-stand-up-for-health/\"><span class=\"s2\">Treadmill Desks: Stand Up For Health</span></a>; <a href=\"https://nutritionfacts.org/2013/11/26/best-nutrition-bang-for-your-buck/\"><span class=\"s2\">Best Nutrition Bang for Your Buck</span></a>; and <a href=\"https://nutritionfacts.org/2013/01/17/diet-vs-exercise-whats-more-important/\"><span class=\"s2\">Diet vs. Exercise: What’s More Important?</span></a></span></p>\n<p>For more on diet and exercise, see: </p>\n<ul>\n<li><a href=\"https://nutritionfacts.org/video/how-much-exercise-to-sustain-weight-loss/\">How Much Exercise to Sustain Weight Loss</a></li>\n<li><a href=\"https://nutritionfacts.org/video/the-role-of-diet-vs-exercise-in-the-obesity-epidemic/\">The Role of Diet vs. Exercise in the Obesity Epidemic</a></li>\n<li><a href=\"https://nutritionfacts.org/video/is-swimming-good-for-weight-loss/\">Is Swimming Good for Weight Loss?</a></li>\n<li><a href=\"https://nutritionfacts.org/video/the-best-time-to-exercise-for-weight-loss/\">The Best Time to Exercise for Weight Loss</a></li>\n<li><a href=\"https://nutritionfacts.org/video/better-to-exercise-before-or-after-meals-for-weight-loss-and-blood-sugar-control/\">Better to Exercise Before or After Meals for Weight Loss and Blood Sugar Control?</a></li>\n</ul>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}
