=== MaximePinot/nutritionfactsorg-data/json/schemas/video.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://nutritionfacts.ouvaton.org/schemas/video.schema.json",
    "title": "Video",
    "description": "A Video article from nutritionfacts.org",
    "type": "object",
    "properties": {
        "Title": {
            "type": "string",
            "minLength": 1
        },
        "Url": {
            "type": "string",
            "minLength": 33,
            "format": "uri",
            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/video\\/"
        },
        "YouTubeVideo": {
            "type": "object",
            "properties": {
                "Url": {
                    "type": "string",
                    "minLength": 24,
                    "format": "uri",
                    "pattern": "^https:\\/\\/(www\\.)?youtube\\.com\\/"
                }
            },
            "required": [
                "Url"
            ],
            "additionalProperties": false
        },
        "UpdatedAt": {
            "type": "string",
            "minLength": 25,
            "maxLength": 25,
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}$"
        },
        "Author": {
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1,
                    "enum": [
                        "Michael Greger M.D. FACLM",
                        "Kristine Dennis PhD, MPH"
                    ]
                }
            ]
        },
        "Volume": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "object",
                    "properties": {
                        "Title": {
                            "type": "string",
                            "minLength": 1
                        },
                        "Url": {
                            "type": "string",
                            "minLength": 35,
                            "format": "uri",
                            "pattern": "^https:\\/\\/nutritionfacts\\.org\\/volumes\\/"
                        }
                    },
                    "required": [
                        "Title",
                        "Url"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "License": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string",
                    "enum": [
                        "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)"
                    ]
                },
                "Url": {
                    "type": "string",
                    "format": "uri",
                    "enum": [
                        "https://creativecommons.org/licenses/by-nc/4.0/"
                    ]
                }
            },
            "required": [
                "Name",
                "Url"
            ],
            "additionalProperties": false
        },
        "Description": {
            "type": "string",
            "minLength": 1
        },
        "Transcript": {
            "type": "string",
            "minLength": 1
        },
        "Sources": {
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "Title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "Url": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "string",
                                "minLength": 1,
                                "format": "uri"
                            }
                        ]
                    }
                },
                "required": [
                    "Title",
                    "Url"
                ],
                "additionalProperties": false
            }
        },
        "Acknowledgements": {
            "type": "string",
            "minLength": 0
        },
        "Topics": {
            "type": "array",
            "items": {
                "type": "object",
                "minItems": 0,
                "uniqueItems": true,
                "properties": {
                    "Title": {
                        "type": "string",
                        "minLength": 1
                    },
                    "Url": {
                        "type": "string",
                        "minLength": 35,
                        "format": "uri",
                        "pattern": "^https:\\/\\/nutritionfacts\\.org\\/topics\\/[\\w-]+\\/$"
                    }
                },
                "required": [
                    "Title",
                    "Url"
                ],
                "additionalProperties": false
            }
        },
        "DoctorsNote": {
            "type": "object",
            "properties": {
                "Html": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "Html"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "Title",
        "Url",
        "YouTubeVideo",
        "UpdatedAt",
        "Author",
        "Volume",
        "License",
        "Description",
        "Transcript",
        "Sources",
        "Acknowledgements",
        "Topics",
        "DoctorsNote"
    ],
    "additionalProperties": false
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/flaxseeds-for-sensitive-skin.json
{
  "Title": "Flaxseeds for Sensitive Skin",
  "Url": "https://nutritionfacts.org/video/flaxseeds-for-sensitive-skin/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/5eKoUkLpE50"
  },
  "UpdatedAt": "2013-04-01T11:35:36+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 12",
    "Url": "https://nutritionfacts.org/volumes/volume-12/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "Instead of treating sensitive skin topically, with lotions and creams, why not treat it from the inside out—with diet?",
  "Transcript": "Below is an approximation of this video’s audio content. To see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring, watch the above video.\nAbout half of the American population says they have sensitive skin, defined loosely as “tingling, chafing, burning,” itching sensations when exposed to various environmental factors. A similar high prevalence has been reported throughout Japan and Europe—especially in women.\nOften, there are no obvious signs, and, so, it’s often been dismissed by the medical community as a “princess and the pea” phenomenon—a mindset that has hindered the investigation of this problem.\nBut, now, it’s largely “recognized as a genuine phenomenon of physiological origin,” thought to arise from an “alteration of the skin barrier allowing potentially irritating substances to penetrate the skin and generate an inflammatory reaction.”\nOkay, so, what can we do about it? Well, recently, supplementation of flaxseed oil was found to diminish skin sensitivity and improve skin barrier function and condition.  In a randomized, double-blind, 12-week study, women were given about a half teaspoon of flaxseed oil a day—internally—versus safflower oil, as a control. That’s the amount of oil found in about a teaspoon and a half of flaxseeds.\nAfter three months, there was a significant decrease in skin reddening in the flax group compared to the safflower group, when an irritant chemical was painted on their forearms to measure skin sensitivity. Their skin also ended up significantly better hydrated, had significantly better barrier function—as evidenced by lower transepidermal water loss—skin that’s less rough; less scaly; and smoother. You can actually see the changes in a close-up view of the skin. Skin looked pretty much just as dry and scaly before and after the safflower oil intervention, but significantly improved after flaxseed oil.\nSensitive skin is typically treated by topical application of lotion and creams. But, why not treat it from the inside? “This study showed that daily supplementation with flaxseed oil improved skin appearance and led to a decreased skin sensitivity by improving epidermal barrier function and decreasing inflammation…”\nThe best source of flaxseed oil is within the flaxseed itself, right?  Then, you get all the nutrition of the whole food, and it’s cheaper and more stable. Unlike the oil, you can bake with the seeds without destroying the omega-3s, and can even store ground flaxseed for a month, at room temperature, without spoilage or oxidation.\nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Dayane de C. Morais, Érica A. Moraes. Heat Treatment and Thirty-Day Storage Period Do Not Affect the Stability of Omega-3 Fatty Acid in Brown Flaxseed (Linum Usitatissimum) Whole Flour. Food and Nutrition Sciences, 2011, 2, 281-286 2011 2(NA):281-286",
      "Url": "http://www.scirp.org/fileOperation/downLoad.aspx?path=FNS20110400005_42622933.pdf&type=journal"
    },
    {
      "Title": "K. Neukam, S. De Spirt, W. Stahl, M. Bejot, J.-M. Maurette, H. Tronnier, U. Heinrich. Supplementation of flaxseed oil diminishes skin sensitivity and improves skin barrier function and condition. Skin Pharmacol Physiol 2011 24(2):67 - 74",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/21088453"
    },
    {
      "Title": "L. Misery, V. Sibaud, C. Merial-Kieny, C. Taieb. Sensitive skin in the American population: Prevalence, clinical data, and role of the dermatologist. Int. J. Dermatol. 2011 50(8):961 - 967",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/21781068"
    },
    {
      "Title": "M. A. Farage, H. I. Maibach. Sensitive skin: Closing in on a physiological cause. Contact Derm. 2010 62(3):137 - 149",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/20565500"
    }
  ],
  "Acknowledgements": "Images thanks to stevendepolo via flickr",
  "Topics": [
    {
      "Title": "Europe",
      "Url": "https://nutritionfacts.org/topics/europe/"
    },
    {
      "Title": "flaxseeds",
      "Url": "https://nutritionfacts.org/topics/flax-seeds/"
    },
    {
      "Title": "inflammation",
      "Url": "https://nutritionfacts.org/topics/inflammation/"
    },
    {
      "Title": "Japan",
      "Url": "https://nutritionfacts.org/topics/japan/"
    },
    {
      "Title": "omega-3 fatty acids",
      "Url": "https://nutritionfacts.org/topics/omega-3-fatty-acids/"
    },
    {
      "Title": "safflower oil",
      "Url": "https://nutritionfacts.org/topics/safflower-oil/"
    },
    {
      "Title": "seeds",
      "Url": "https://nutritionfacts.org/topics/seeds/"
    },
    {
      "Title": "skin health",
      "Url": "https://nutritionfacts.org/topics/skin-health/"
    },
    {
      "Title": "women's health",
      "Url": "https://nutritionfacts.org/topics/womens-health/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>I bet one of the reasons the medical community was so dismissive is because of the preponderance of sensitive skin in women. Did you see my video about how the profession used to treat menopause? Ghastly: <a title=\"Permanent link to Plant-Based Bioidentical Hormones\" href=\"https://nutritionfacts.org/video/plant-based-bioidentical-hormones/\">Plant-Based Bioidentical Hormones</a>.</p>\n<p>For more on eating your way towards healthier skin, see:</p>\n<ul>\n<li><a title=\"Permanent link to Rosy Glow\" href=\"https://nutritionfacts.org/video/rosy-glow/\">Rosy Glow</a></li>\n<li><a title=\"Permanent link to Golden Glow\" href=\"https://nutritionfacts.org/video/golden-glow/\">Golden Glow</a></li>\n<li><a title=\"Permanent link to Skim Milk and Acne\" href=\"https://nutritionfacts.org/video/skim-milk-and-acne/\">Skim Milk and Acne</a></li>\n<li><a title=\"Permanent link to Preventing Wrinkles with Diet\" href=\"https://nutritionfacts.org/video/preventing-wrinkles-with-diet/\">Preventing Wrinkles with Diet</a></li>\n<li><a title=\"Permanent link to Beauty Is More Than Skin Deep\" href=\"https://nutritionfacts.org/video/beauty-is-more-than-skin-deep/\">Beauty Is More Than Skin Deep</a></li>\n<li><a title=\"Permanent link to Produce, Not Pills to Increase Physical Attractiveness\" href=\"https://nutritionfacts.org/video/produce-not-pills-to-increase-physical-attractiveness/\">Produce, Not Pills to Increase Physical Attractiveness</a></li>\n</ul>\n<p>For more on flax, see my last three videos: <a href=\"https://nutritionfacts.org/video/flaxseed-vs-prostate-cancer/\">Flax Seeds vs. Prostate Cancer</a>; <a href=\"https://nutritionfacts.org/video/was-it-the-flaxseed-fat-restriction-or-both/\">Was It the Flax Seed, Fat Restriction, or Both?</a>; and <a href=\"https://nutritionfacts.org/video/flaxseed-vs-diabetes/\">Flax Seed vs. Diabetes</a>. Sick of flax videos already? No problem! Stay tuned for my next video, <a href=\"https://nutritionfacts.org/video/fiber-vs-breast-cancer/\">Fiber vs. Breast Cancer</a>.</p>\n<p>For further context, also check out my associated blog posts: <a href=\"https://nutritionfacts.org/2013/10/10/flaxseeds-for-sensitive-skin/\">Treating Sensitive Skin From the Inside Out</a>; <a href=\"https://nutritionfacts.org/2013/10/15/flaxseeds-for-breast-cancer-prevention/\">Flax and Breast Cancer Prevention</a>; and <a href=\"https://nutritionfacts.org/2013/10/17/flaxseeds-breast-cancer-survival/\">Flax and Breast Cancer Survival</a>.</p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}

=== MaximePinot/nutritionfactsorg-data/json/data/video/tipping-the-balance-of-firmicutes-to-bacteroidetes.json
{
  "Title": "Tipping Firmicutes to Bacteroidetes",
  "Url": "https://nutritionfacts.org/video/tipping-the-balance-of-firmicutes-to-bacteroidetes/",
  "YouTubeVideo": {
    "Url": "https://www.youtube.com/embed/jNEg47o1VeQ"
  },
  "UpdatedAt": "2012-08-30T10:49:27+00:00",
  "Author": "Michael Greger M.D. FACLM",
  "Volume": {
    "Title": "Volume 10",
    "Url": "https://nutritionfacts.org/volumes/volume-10/"
  },
  "License": {
    "Name": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "Url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  "Description": "Certain phytonutrients may tip the balance of healthy gut bacteria in favor of flora associated with improved weight control.",
  "Transcript": "Other than fiber, what else do plants make that animals don’t, that could help account for how dramatically slimmer those who eat plant-based diets tend to be? Phytonutrients!\nMammals, including humans, harbor two main types of friendly gut bacteria: Bacteroidetes and Firmicutes. In terms of obesity, though, one appears friendlier than the other. There is mounting evidence that the gut flora is different in healthy patients than it is in obese patients, which primarily involves higher numbers of Firmicutes than Bacteroidetes phyla, in the case of obesity and overweight. So, just to keep them straight, you can remember: fatter, Firmicutes; and bonier, Bacteroidetes.\nObese individuals seem to have more Firmicutes than Bacteriodetes in their guts. If you put people on a diet for a year, you can actually change the proportion. Give people certain antibiotics; you may actually trigger obesity, because you’re mucking around down there.\nHow can we improve our ratio? Well, there is a class of phytonutrients, called polyphenols, that do two things: they preferentially feed Bacteriodetes, while at the same time suppressing the growth of Firmicutes.\nSo researchers were like, hey, maybe that’s why the use of vinegar has been recommended for thousands of years for weight loss! What’s it often made out of ?Red wine vinegar, apple cider vinegar—both of which, grapes and apples, packed with polyphenols. The weight-lowering properties of fruits, green tea, and wine vinegar in obese people may be partly related to the polyphenol content of them—which consequently changes the gut flora, which may consequently alter the balance between the two groups of Bacteroidetes and the Firmicutes bacteria, in the favor of Bacteroidetes.\nIt’s funny; you know, naysayers of the power of phytonutrients often point to studies like this, showing that up to 85% of those wonderful blue anthocyanins in blueberries end up in your colon, unabsorbed. But that may be exactly where some of the magic happens.\nTo see any graphs, charts, graphics, images, and quotes to which Dr. Greger may be referring, watch the above video. This is just an approximation of the audio contributed by MaryAnn Allison.\nPlease consider volunteering to help out on the site.",
  "Sources": [
    {
      "Title": "Kahle K, Kraus M, Scheppach W, Ackermann M, Ridder F, Richling E. Studies on apple and blueberry fruit constituents: do the polyphenols reach the colon after ingestion? Mol Nutr Food Res. 2006 Apr;50(4-5):418-23.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/16548015"
    },
    {
      "Title": "Ley RE, Turnbaugh PJ, Klein S, Gordon JI. Microbial ecology: human gut microbes associated with obesity. Nature. 2006 Dec 21;444(7122):1022-3.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/17183309"
    },
    {
      "Title": "Rastmanesh R. High polyphenol, low probiotic diet for weight loss because of intestinal microbiota interaction. Chem Biol Interact. 2011 Jan 15;189(1-2):1-8.",
      "Url": "http://www.ncbi.nlm.nih.gov/pubmed/20955691"
    },
    {
      "Title": "Thuny F, Richet H, Casalta JP, Angelakis E, Habib G, Raoult D. Vancomycin treatment of infective endocarditis is linked with recently acquired obesity. PLoS One. 2010 Feb 10;5(2):e9074.",
      "Url": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2818846/pdf/pone.0009074.pdf"
    }
  ],
  "Acknowledgements": "",
  "Topics": [
    {
      "Title": "antibiotics",
      "Url": "https://nutritionfacts.org/topics/antibiotics/"
    },
    {
      "Title": "apples",
      "Url": "https://nutritionfacts.org/topics/apples/"
    },
    {
      "Title": "bile acids",
      "Url": "https://nutritionfacts.org/topics/bile-acids/"
    },
    {
      "Title": "blueberries",
      "Url": "https://nutritionfacts.org/topics/blueberries/"
    },
    {
      "Title": "body fat",
      "Url": "https://nutritionfacts.org/topics/body-fat/"
    },
    {
      "Title": "colon health",
      "Url": "https://nutritionfacts.org/topics/colon-health/"
    },
    {
      "Title": "fiber",
      "Url": "https://nutritionfacts.org/topics/fiber/"
    },
    {
      "Title": "fruit",
      "Url": "https://nutritionfacts.org/topics/fruit/"
    },
    {
      "Title": "grapes",
      "Url": "https://nutritionfacts.org/topics/grapes/"
    },
    {
      "Title": "green tea",
      "Url": "https://nutritionfacts.org/topics/green-tea/"
    },
    {
      "Title": "gut flora",
      "Url": "https://nutritionfacts.org/topics/gut-flora/"
    },
    {
      "Title": "microbiome",
      "Url": "https://nutritionfacts.org/topics/microbiome/"
    },
    {
      "Title": "obesity",
      "Url": "https://nutritionfacts.org/topics/obesity/"
    },
    {
      "Title": "phytonutrients",
      "Url": "https://nutritionfacts.org/topics/phytonutrients/"
    },
    {
      "Title": "Plant-Based Diets",
      "Url": "https://nutritionfacts.org/topics/plant-based-diets/"
    },
    {
      "Title": "polyphenols",
      "Url": "https://nutritionfacts.org/topics/polyphenols/"
    },
    {
      "Title": "probiotics",
      "Url": "https://nutritionfacts.org/topics/probiotics/"
    },
    {
      "Title": "vegans",
      "Url": "https://nutritionfacts.org/topics/vegans/"
    },
    {
      "Title": "vegetarians",
      "Url": "https://nutritionfacts.org/topics/vegetarians/"
    },
    {
      "Title": "vinegar",
      "Url": "https://nutritionfacts.org/topics/vinegar/"
    },
    {
      "Title": "weight loss",
      "Url": "https://nutritionfacts.org/topics/weight-loss/"
    }
  ],
  "DoctorsNote": {
    "Html": "<p>This is the third of a three-part video series on keeping our gut bacteria happy. The first two discussed propionate (see <a href=\"https://nutritionfacts.org/video/fawning-over-flora/\">Fawning Over Flora</a>), and butyrate (see <a href=\"https://nutritionfacts.org/video/boosting-good-bacteria-in-the-colon-without-probiotics/\">Boosting Good Bacteria in the Colon Without Probiotics</a>)—two health-promoting short-chain fatty acids produced by the fermentation of fiber that may be helpful in preventing obesity, cancer, and inflammation in general. More on phenolic phytonutrients in <a href=\"https://nutritionfacts.org/video/best-fruit-juice/\" rel=\"nofollow\">Best Fruit Juice</a>. Are blueberries the <a href=\"https://nutritionfacts.org/video/best-berries/\" rel=\"nofollow\">Best Berries</a>?</p>\n<p>For more context, check out my associated blog posts: <a href=\"https://nutritionfacts.org/blog/the-ice-diet/\"> The Ice Diet</a> and <a href=\"https://nutritionfacts.org/blog/eating-green-to-prevent-cancer/\">Eating Green to Prevent Cancer</a>.</p>\n     <p>If you haven&#39;t yet, you can <a href=\"https://nutritionfacts.org/subscribe/\" title=\"Subscribe\">subscribe to our free newsletter</a>. With your subscription, you&#39;ll also get notifications for just-released blogs and videos. Check out our <a href=\"https://nutritionfacts.org/translations-info/\" target=\"_blank\" title=\"Translated Resources\">information page</a> about our translated resources.</p>"
  }
}
